/* Bottifact · evidencia editorial. SVG local, tablas como fuente; sin RAF ni red. */
(()=>{'use strict';
 const instances=new WeakMap(),NS='http://www.w3.org/2000/svg',fmt={format:v=>new Intl.NumberFormat('es-CO',{maximumSignificantDigits:8,notation:v!==0&&(Math.abs(v)<.001||Math.abs(v)>1e9)?'scientific':'standard'}).format(v)};
 const make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 const svg=(tag,attrs={},text)=>{const e=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;return e;};
 const number=(cell)=>{const raw=cell?.dataset.valor??cell?.textContent?.trim();if(raw===undefined||raw===''||!Number.isFinite(Number(raw))||Math.abs(Number(raw))>1e12)throw Error('Cada valor requiere un número finito de hasta 10¹².');return Number(raw);};
 const label=cell=>{const s=cell?.textContent.trim();if(!s||s.length>100)throw Error('Usa nombres de 1 a 100 caracteres.');return s;};
 const day=cell=>{const s=cell?.querySelector('time')?.dateTime||cell?.textContent.trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))throw Error('Las fechas deben ser YYYY-MM-DD.');const t=Date.parse(s+'T00:00:00Z');if(!Number.isFinite(t)||new Date(t).toISOString().slice(0,10)!==s)throw Error('Fecha inexistente.');return t;};
 const date=t=>new Date(t).toISOString().slice(0,10),pct=v=>fmt.format(v*100)+' %',amount=(v,u)=>fmt.format(v)+(u?' '+u:'');
 function rows(root,min,max,columns){if(root.querySelectorAll('table[data-evidencia-datos]').length!==1)throw Error('Se requiere una sola tabla fuente.');const rs=[...root.querySelectorAll('table[data-evidencia-datos] > tbody > tr')];if(rs.length<min||rs.length>max)throw Error(`Se requieren ${min}–${max} filas.`);return rs.map(r=>{const cells=[...r.cells];if(columns&&cells.length!==columns)throw Error(`Se requieren ${columns} columnas por fila.`);return cells;});}
 function wrapped(text,width=26){let lines=[''];for(const word of text.split(/\s+/)){const chunks=word.match(new RegExp('.{1,'+width+'}','g'))||[''];for(const chunk of chunks){if((lines.at(-1)+' '+chunk).trim().length>width)lines.push(chunk);else lines[lines.length-1]=(lines.at(-1)+' '+chunk).trim();}}return lines;}
 function wrap(s,text,x,y,width=26){const lines=wrapped(text,width),t=svg('text',{x,y});lines.forEach((line,i)=>t.append(svg('tspan',{x,dy:i?15:0},line)));s.append(t);return lines.length;}
 function domain(values,zero=false){let lo=Math.min(...values, ...(zero?[0]:[])),hi=Math.max(...values,...(zero?[0]:[]));if(lo===hi){const d=Math.max(1,Math.abs(lo)*.1);lo-=d;hi+=d;}return [lo,hi];}
 const scale=([lo,hi],start,end)=>v=>start+(v-lo)/(hi-lo)*(end-start);
 function axis(s,d,x,y,width,unit='',dates=false){const fn=scale(d,x,x+width);s.append(svg('line',{x1:x,y1:y,x2:x+width,y2:y,class:'ev-eje'}));const ticks=[...new Set(Array.from({length:5},(_,i)=>{const v=d[0]+(d[1]-d[0])*i/4;return dates?Math.round(v/86400000)*86400000:v;}))];ticks.forEach((v,i)=>{const xx=fn(v);s.append(svg('line',{x1:xx,y1:y,x2:xx,y2:y-8,class:'ev-eje'}),svg('text',{x:xx,y:y+23,'text-anchor':i===0?'start':i===ticks.length-1?'end':'middle'},dates?date(v):fmt.format(v)));});if(unit)s.append(svg('text',{x,y:y+46},unit));return fn;}
 function canvas(ctx,width,height,description){const s=svg('svg',{viewBox:`0 0 ${width} ${height}`,width,height,role:'img','aria-label':description});s.append(svg('title',{},description));ctx.view.style.setProperty('--ev-ancho',width+'px');ctx.view.replaceChildren(s);return s;}
 function mark(ctx,s,node,index,description){node.classList.add('ev-marca');node.dataset.evRow=index;node.append(svg('title',{},description));s.append(node);ctx.on(node,'click',()=>ctx.choose(index));return node;}
 function selection(ctx,labels,descriptions,custom){const l=make('label','Consultar dato '),sel=make('select');sel.setAttribute('aria-label','Consultar dato de '+ctx.title);labels.forEach((name,i)=>{const o=make('option',name);o.value=i;sel.append(o);});l.append(sel);ctx.tools.append(l);ctx.choose=i=>{i=Math.max(0,Math.min(labels.length-1,Number(i)||0));sel.value=i;ctx.selected=i;ctx.detail.textContent=descriptions[i];ctx.view.querySelectorAll('[data-ev-row]').forEach(n=>n.classList.toggle('ev-elegido',Number(n.dataset.evRow)===i));custom?.(i);};ctx.on(sel,'change',()=>ctx.choose(sel.value));ctx.choose(0);return sel;}
 function sankey(ctx){
  const rs=rows(ctx.root,1,24,3),data=rs.map(c=>({a:label(c[0]),b:label(c[1]),v:number(c[2])}));if(data.some(d=>d.v<0))throw Error('Sankey requiere magnitudes no negativas.');
  const total=data.reduce((a,d)=>a+d.v,0);if(total<=0||total>1e12)throw Error('El total debe ser positivo y no superar 10¹².');
  const left=[...new Set(data.map(d=>d.a))],right=[...new Set(data.map(d=>d.b))];if(Math.max(left.length,right.length)>8)throw Error('Máximo ocho nodos por columna.');
  const n=Math.max(left.length,right.length),gap=Math.max(40,...[...left,...right].map(name=>wrapped(name,24).length*15+20)),h=Math.max(320,n*100),k=(h-(n-1)*gap)/total,s=canvas(ctx,840,h+gap+100,ctx.title+'; grosor proporcional; '+amount(total,ctx.unit)+' en total.');
  const layout=(names,key)=>{let y=65;return new Map(names.map(name=>{const v=data.filter(d=>d[key]===name).reduce((a,d)=>a+d.v,0),node={y,v,offset:0};y+=v*k+gap;return [name,node];}));},a=layout(left,'a'),b=layout(right,'b');
  data.forEach((d,i)=>{const from=a.get(d.a),to=b.get(d.b),thick=d.v*k,y1=from.y+from.offset+thick/2,y2=to.y+to.offset+thick/2;from.offset+=thick;to.offset+=thick;if(d.v)mark(ctx,s,svg('path',{d:`M236 ${y1} C380 ${y1} 460 ${y2} 604 ${y2}`,class:'ev-flujo ev-color-'+left.indexOf(d.a)%4,'stroke-width':thick,fill:'none'}),i,`${d.a} → ${d.b}: ${amount(d.v,ctx.unit)}`);});
  for(const [map,x,tx] of [[a,222,12],[b,604,632]])for(const [name,d] of map){s.append(svg('rect',{x,y:d.y,width:14,height:d.v*k,class:'ev-nodo'}));const lines=wrap(s,name,tx,d.y+8,24);s.append(svg('text',{x:tx,y:d.y+20+lines*15},amount(d.v,ctx.unit)));}
  selection(ctx,data.map(d=>d.a+' → '+d.b),data.map(d=>`${d.a} → ${d.b}: ${amount(d.v,ctx.unit)}. ${pct(d.v/total)} del total ${amount(total,ctx.unit)}.`));ctx.model={total,scale:k,links:data};
 }
 function cohorts(ctx){
  const rs=rows(ctx.root,1,20),cols=rs[0].length-2;if(cols<1||cols>12||rs.some(c=>c.length!==cols+2))throw Error('Cohortes requiere nombre, base y 1–12 períodos iguales.');
  const heads=[...ctx.root.querySelectorAll('table[data-evidencia-datos] thead th')].slice(2).map(label);if(heads.length!==cols||heads.some(h=>h.length>24))throw Error('Cada período necesita cabecera.');
  const data=rs.map(c=>{const base=number(c[1]);if(!Number.isInteger(base)||base<=0)throw Error('La base de cohorte debe ser un entero positivo.');let missing=false;const values=c.slice(2).map(v=>{if(v.dataset.estado==='pendiente'){missing=true;return null;}if(missing)throw Error('Los períodos pendientes deben quedar al final de la fila.');const x=number(v);if(!Number.isInteger(x)||x<0||x>base)throw Error('Recuentos de cohorte entre cero y su base.');return x;});return {name:label(c[0]),base,values};});
  const cw=Math.max(110,...data.flatMap(d=>d.values.map(v=>v===null?110:((String(v).length+String(d.base).length+3)*7.5+20))));const rh=Math.max(68,...data.map(d=>wrapped(d.name,24).length*15+38));const s=canvas(ctx,250+cols*cw,100+data.length*rh,ctx.title+'; porcentaje respecto a la base de cada cohorte. Pendiente no equivale a cero.'),labels=[],descriptions=[];
  heads.forEach((x,i)=>wrap(s,x,250+i*cw,25,12));data.forEach((d,r)=>{const lines=wrap(s,d.name,12,80+r*rh,24);s.append(svg('text',{x:12,y:88+lines*15+r*rh},'Base '+fmt.format(d.base)));d.values.forEach((v,c)=>{const x=250+c*cw,y=58+r*rh,ratio=v===null?null:v/d.base,index=labels.length;labels.push(d.name+' · '+heads[c]);descriptions.push(v===null?`${d.name}, ${heads[c]}: pendiente de observar; base ${d.base}.`:`${d.name}, ${heads[c]}: ${v} de ${d.base}; ${pct(ratio)}.`);const g=svg('g');g.append(svg('rect',{x,y,width:cw-6,height:rh-6,class:v===null?'ev-ausente':'ev-calor ev-nivel-'+Math.min(4,Math.floor(ratio*5))}),svg('text',{x:x+(cw-6)/2,y:y+28,'text-anchor':'middle',class:'ev-calor-texto'},v===null?'Pendiente':pct(ratio)),svg('text',{x:x+(cw-6)/2,y:y+49,'text-anchor':'middle',class:'ev-calor-texto'},v===null?'sin observar':`${v} / ${d.base}`));mark(ctx,s,g,index,descriptions.at(-1));});});
  const legend=make('p','Escala: 0–<20 %, 20–<40 %, 40–<60 %, 60–<80 %, 80–100 %. Contorno discontinuo: pendiente.');legend.className='evidencia-leyenda';ctx.view.after(legend);selection(ctx,labels,descriptions);ctx.model={data,periods:heads};
 }
 function sensitivity(ctx){
  const baseCell=ctx.root.querySelector('[data-evidencia-base]');if(!baseCell)throw Error('Falta el resultado base visible.');const base=number(baseCell),rs=rows(ctx.root,1,16,5);
  const data=rs.map(c=>({name:label(c[0]),low:label(c[1]),a:number(c[2]),high:label(c[3]),b:number(c[4])}));
  data.sort((a,b)=>Math.abs(b.b-b.a)-Math.abs(a.b-a.a));const d=domain([base,...data.flatMap(x=>[x.a,x.b])]),h=95+data.length*78,s=canvas(ctx,860,h+80,ctx.title+'; un supuesto cambia a la vez; resultado base '+amount(base,ctx.unit)),x=axis(s,d,260,h,570,ctx.unit);
  s.append(svg('line',{x1:x(base),x2:x(base),y1:45,y2:h,class:'ev-base'}));s.append(svg('text',{x:260,y:25},'Base: '+amount(base,ctx.unit)+' · círculos A / cuadrados B'));
  data.forEach((v,i)=>{const y=74+i*78;wrap(s,v.name,12,y,27);const g=svg('g');g.append(svg('line',{x1:x(v.a),x2:x(v.b),y1:y,y2:y,class:'ev-intervalo'}),svg('circle',{cx:x(v.a),cy:y,r:6,class:'ev-punto'}),svg('rect',{x:x(v.b)-6,y:y-6,width:12,height:12,class:'ev-punto ev-color-1'}));mark(ctx,s,g,i,v.name);s.append(svg('text',{x:260,y:y+28},'A: '+fmt.format(v.a)+' · B: '+fmt.format(v.b)));});
  const descriptions=data.map(v=>`${v.name}. A (${v.low}): ${amount(v.a,ctx.unit)}, cambio ${amount(v.a-base,ctx.unit)}. B (${v.high}): ${amount(v.b,ctx.unit)}, cambio ${amount(v.b-base,ctx.unit)}. Base ${amount(base,ctx.unit)}. No combina supuestos.`);
  selection(ctx,data.map(d=>d.name),descriptions);const reset=make('button','Restablecer consulta');reset.type='button';ctx.on(reset,'click',()=>ctx.choose(0));ctx.tools.append(reset);ctx.model={base,domain:d,data};
 }
 function gantt(ctx){
  const rs=rows(ctx.root,1,24,7),data=rs.map(c=>({id:label(c[0]),name:label(c[1]),start:day(c[2]),end:day(c[3]),owner:label(c[4]),state:label(c[5]),deps:c[6].textContent.trim()==='—'?[]:c[6].textContent.trim().split(/\s*,\s*/)}));
  const map=new Map(data.map(d=>[d.id,d]));if(map.size!==data.length||data.some(d=>!/^[-\w]{1,12}$/.test(d.id)||d.end<d.start||!['Plan','En curso','Completada'].includes(d.state)))throw Error('IDs únicos, fin ≥ inicio y estados Plan / En curso / Completada.');
  const visiting=new Set(),done=new Set();function visit(d){if(visiting.has(d.id))throw Error('Las dependencias no pueden formar ciclos.');if(done.has(d.id))return;visiting.add(d.id);for(const id of d.deps){if(!map.has(id))throw Error('Dependencia inexistente: '+id);if(d.start<map.get(id).end)throw Error('Una dependencia fin→inicio no puede terminar después del inicio dependiente.');visit(map.get(id));}visiting.delete(d.id);done.add(d.id);}data.forEach(visit);
  let d=[Math.min(...data.map(v=>v.start)),Math.max(...data.map(v=>v.end))];if(d[0]===d[1])d[1]+=86400000;if(d[1]-d[0]>3660*86400000)throw Error('El Gantt admite hasta diez años.');
  const rh=Math.max(76,...data.map(d=>wrapped(d.id+' · '+d.name,30).length*15+38)),h=95+data.length*rh,s=canvas(ctx,940,h+80,ctx.title+'; fechas UTC, intervalos inicio a fin y dependencias fin a inicio.'),x=axis(s,d,300,h,610,'Fechas UTC · símbolos: ○ plan, ◐ en curso, ● completada',true);
  data.forEach((v,i)=>v.deps.forEach(id=>{const j=data.findIndex(t=>t.id===id),from=data[j],a=x(from.end),b=x(v.start),yy=50+j*rh,y=50+i*rh;const elbow=Math.min(b,Math.max(300,a+10));s.append(svg('path',{d:`M${a} ${yy} H${elbow} V${y} H${b}`,class:'ev-dependencia'}),svg('path',{d:`M${b-6} ${y-4} L${b} ${y} L${b-6} ${y+4}`,class:'ev-dependencia'}));}));
  data.forEach((v,i)=>{const y=50+i*rh;const lines=wrap(s,v.id+' · '+v.name,12,y-8,30);s.append(svg('text',{x:12,y:y+10+lines*15},({'Plan':'○','En curso':'◐','Completada':'●'})[v.state]+' '+v.state));const g=svg('g');if(v.end===v.start)g.append(svg('path',{d:`M${x(v.start)} ${y-8} l8 8 -8 8 -8 -8 Z`,class:'ev-solido'}));else g.append(svg('rect',{x:x(v.start),y:y-9,width:x(v.end)-x(v.start),height:18,rx:2,class:'ev-solido'}));mark(ctx,s,g,i,v.name);});
  selection(ctx,data.map(d=>d.id+' · '+d.name),data.map(v=>`${v.name}: ${date(v.start)} → ${date(v.end)} (${fmt.format((v.end-v.start)/86400000)} días transcurridos). ${v.owner}. ${v.state}. Depende de: ${v.deps.join(', ')||'ninguna'}.`));ctx.model={data,domain:d};
 }
 function funnel(ctx){
  const data=rows(ctx.root,2,12,3).map(c=>({name:label(c[0]),v:number(c[1]),meaning:label(c[2])}));if(data[0].v<=0||data.some((d,i)=>!Number.isInteger(d.v)||d.v<0||(i&&d.v>data[i-1].v)))throw Error('El embudo exige recuentos enteros no crecientes y base positiva.');
  const max=data[0].v,h=80+data.length*84,s=canvas(ctx,880,h+80,ctx.title+'; ancho proporcional al recuento; cero común.'),x=axis(s,[0,max],260,h,580,ctx.unit);
  const desc=data.map((v,i)=>`${v.name}: ${amount(v.v,ctx.unit)}; ${pct(v.v/max)} de la base.${i?' Conversión desde la anterior: '+(data[i-1].v?pct(v.v/data[i-1].v):'no definida (base cero)')+'; abandono '+amount(data[i-1].v-v.v,ctx.unit)+'.':''} ${v.meaning}`);
  data.forEach((v,i)=>{const y=40+i*84;wrap(s,v.name,12,y+8,26);mark(ctx,s,svg('rect',{x:260,y,width:x(v.v)-260,height:24,class:'ev-solido'}),i,desc[i]);s.append(svg('text',{x:260,y:y+47},fmt.format(v.v)+' · '+pct(v.v/max)+' de la base'));});selection(ctx,data.map(d=>d.name),desc);ctx.model={data,base:max};
 }
 function uncertainty(ctx){
  if(!ctx.root.querySelector('[data-evidencia-metodo]')?.textContent.trim())throw Error('Explica cómo se construyó el intervalo.');
  const data=rows(ctx.root,2,48,4).map(c=>({t:day(c[0]),low:number(c[1]),v:number(c[2]),high:number(c[3])}));if(data.some((d,i)=>d.low>d.v||d.v>d.high||(i&&d.t<=data[i-1].t)))throw Error('Fechas estrictamente crecientes y límite inferior ≤ central ≤ superior.');
  const yd=domain(data.flatMap(d=>[d.low,d.high])),xd=[data[0].t,data.at(-1).t],s=canvas(ctx,960,460,ctx.title+'; banda de escenarios declarados, sin probabilidad implícita.'),x=axis(s,xd,190,360,720,'Fecha UTC',true),y=scale(yd,330,40);
  for(let i=0;i<=4;i++){const v=yd[0]+(yd[1]-yd[0])*i/4,yy=y(v);s.append(svg('line',{x1:190,y1:yy,x2:910,y2:yy,class:'ev-rejilla'}),svg('text',{x:178,y:yy+4,'text-anchor':'end'},fmt.format(v)));}s.append(svg('text',{x:190,y:20},ctx.unit));
  s.append(svg('path',{d:'M'+data.map(d=>`${x(d.t)} ${y(d.high)}`).join(' L')+' L'+[...data].reverse().map(d=>`${x(d.t)} ${y(d.low)}`).join(' L')+' Z',class:'ev-banda'}));
  for(const key of ['low','high','v'])s.append(svg('path',{d:'M'+data.map(d=>`${x(d.t)} ${y(d[key])}`).join(' L'),class:key==='v'?'ev-central':'ev-limite'}));
  const desc=data.map(d=>`${date(d.t)}: inferior ${amount(d.low,ctx.unit)}, central ${amount(d.v,ctx.unit)}, superior ${amount(d.high,ctx.unit)}.`);
  data.forEach((d,i)=>mark(ctx,s,svg('circle',{cx:x(d.t),cy:y(d.v),r:5,class:'ev-punto'}),i,desc[i]));selection(ctx,data.map(d=>date(d.t)),desc);ctx.model={data,domain:yd};
 }
 function story(ctx){
  const data=rows(ctx.root,2,8,3).map(c=>({name:label(c[0]),v:number(c[1]),text:label(c[2])}));if(data.some(d=>d.v<0)||Math.max(...data.map(d=>d.v))===0)throw Error('El relato requiere magnitudes no negativas y algún valor positivo.');
  const h=70+data.length*100,s=canvas(ctx,560,h+75,ctx.title+'; todos los pasos comparten escala.'),x=axis(s,[0,Math.max(...data.map(d=>d.v))],170,h,370,ctx.unit);
  data.forEach((d,i)=>{const y=35+i*100;wrap(s,d.name,12,y+14,18);mark(ctx,s,svg('rect',{x:170,y,width:x(d.v)-170,height:24,class:'ev-solido'}),i,d.text);s.append(svg('text',{x:170,y:y+45},amount(d.v,ctx.unit)));});
  const steps=make('ol');steps.className='relato-pasos';ctx.ui.append(steps);const buttons=[];
  data.forEach((d,i)=>{const li=make('li'),b=make('button',d.name);b.type='button';const p=make('p',amount(d.v,ctx.unit)+'. '+d.text);li.append(b,p);steps.append(li);buttons.push(b);ctx.on(b,'click',()=>{manual.checked=true;ctx.choose(i);});});
  const control=make('label'),manual=make('input');manual.type='checkbox';control.append(manual,make('span',' Elegir pasos manualmente'));ctx.tools.append(control);
  const select=selection(ctx,data.map(d=>d.name),data.map(d=>`${d.name}: ${amount(d.v,ctx.unit)}. ${d.text}`),i=>{buttons.forEach((b,j)=>{b.setAttribute('aria-pressed',String(i===j));b.closest('li').classList.toggle('relato-actual',i===j);});});ctx.on(select,'change',()=>{manual.checked=true;});
  ctx.detail.setAttribute('aria-live','off');ctx.ui.classList.add('ev-relato');
  const io=new IntersectionObserver(entries=>{if(manual.checked||document.hidden)return;const visible=entries.filter(e=>e.isIntersecting);if(visible.length){const near=visible.sort((a,b)=>Math.abs(a.boundingClientRect.top-innerHeight*.45)-Math.abs(b.boundingClientRect.top-innerHeight*.45))[0];ctx.choose([...steps.children].indexOf(near.target));}},{rootMargin:'-25% 0px -35% 0px',threshold:0});[...steps.children].forEach(li=>io.observe(li));ctx.clean.push(()=>io.disconnect());ctx.model={data};
 }
 function image(ctx){
  const source=ctx.root.querySelector('[data-evidencia-imagen] img'),list=ctx.root.querySelector('[data-evidencia-zonas]');if(!source||!/^data:image\//.test(source.getAttribute('src')||'')||!list)throw Error('Se requiere una imagen incrustada y lista de zonas.');
  const zones=[...list.children].map(li=>({x:Number(li.dataset.x),y:Number(li.dataset.y),text:label(li)}));if(zones.length<1||zones.length>12||zones.some(d=>!Number.isFinite(d.x)||!Number.isFinite(d.y)||d.x<0||d.x>100||d.y<0||d.y>100))throw Error('Usa 1–12 zonas, con coordenadas porcentuales de 0 a 100.');
  const holder=source.parentElement,oldHidden=holder.hidden;holder.hidden=true;ctx.clean.push(()=>{holder.hidden=oldHidden;});
  ctx.view.classList.add('ev-imagen-visor');const sheet=make('div'),img=source.cloneNode(true);img.removeAttribute('id');sheet.className='ev-lamina';sheet.append(img);ctx.view.append(sheet);let zoom=1;const read=make('output');read.setAttribute('aria-label','Ampliación de imagen');
  const setZoom=value=>{zoom=Math.max(1,Math.min(4,value));sheet.style.width=(100*zoom)+'%';read.textContent=Math.round(zoom*100)+' %';if(ctx.selected!==undefined)focusZone(ctx.selected);};
  function focusZone(i){const d=zones[i];ctx.view.scrollLeft=Math.max(0,sheet.clientWidth*d.x/100-ctx.view.clientWidth/2);ctx.view.scrollTop=Math.max(0,sheet.clientHeight*d.y/100-ctx.view.clientHeight/2);}
  for(const [name,fn] of [['Ampliar imagen',()=>setZoom(zoom+.5)],['Reducir imagen',()=>setZoom(zoom-.5)],['Ajustar imagen',()=>setZoom(1)]]){const b=make('button',name==='Ampliar imagen'?'+':name==='Reducir imagen'?'−':'↺');b.type='button';b.className='nota-icono';b.title=name;b.setAttribute('aria-label',name);ctx.tools.append(b);ctx.on(b,'click',fn);}ctx.tools.append(read);
  zones.forEach((d,i)=>{const b=make('button',String(i+1));b.type='button';b.className='ev-pin';b.style.left=d.x+'%';b.style.top=d.y+'%';b.dataset.evRow=i;b.setAttribute('aria-label',`Zona ${i+1}: ${d.text}`);sheet.append(b);ctx.on(b,'click',()=>ctx.choose(i));});
  selection(ctx,zones.map((d,i)=>`${i+1}. ${d.text}`),zones.map((d,i)=>`Zona ${i+1}: ${d.text}`),focusZone);ctx.on(img,'load',()=>focusZone(ctx.selected||0));setZoom(1);ctx.model={zones,get zoom(){return zoom;}};
 }
 const renderers={sankey,cohortes:cohorts,sensibilidad:sensitivity,gantt,embudo:funnel,incertidumbre:uncertainty,relato:story,imagen:image};
 function init(root=document){return [...(root.matches?.('[data-evidencia]')?[root]:[]),...root.querySelectorAll('[data-evidencia]')].map(el=>{if(instances.has(el))return instances.get(el);const abort=new AbortController(),clean=[],ui=make('div'),tools=make('div'),view=make('div'),detail=make('p');ui.className='evidencia-ui';tools.className='evidencia-controles';view.className='evidencia-visor';detail.className='evidencia-detalle';detail.setAttribute('role','status');detail.setAttribute('aria-live','polite');view.tabIndex=0;view.setAttribute('role','region');const title=el.querySelector('table caption,h3')?.textContent.trim()||'Evidencia';view.setAttribute('aria-label',title+', desplazable');ui.append(tools,view,detail);el.prepend(ui);
   const ctx={root:el,title,unit:el.dataset.unidad||'',ui,tools,view,detail,clean,selected:undefined,choose:()=>{},on:(node,type,fn,options={})=>node.addEventListener(type,fn,{...options,signal:abort.signal})};
   const instance={get model(){return ctx.model;},get selected(){return ctx.selected;},select:i=>ctx.choose(i),destroy(){abort.abort();clean.forEach(fn=>fn());ui.remove();instances.delete(el);}};instances.set(el,instance);
   try{if(el.dataset.evidencia!=='imagen'&&(!ctx.unit.trim()||ctx.unit.length>40))throw Error('Declara una unidad de 1 a 40 caracteres.');if(!renderers[el.dataset.evidencia])throw Error('Tipo de evidencia desconocido.');renderers[el.dataset.evidencia](ctx);}
   catch(error){abort.abort();clean.forEach(fn=>fn());ui.replaceChildren(make('p','No se dibujó esta vista: '+error.message+' Los datos originales siguen disponibles.'));ui.classList.add('evidencia-error');instance.error=error.message;}
   return instance;
  });}
 window.NotaEvidencia={init,get:el=>instances.get(el)};init();
})();
