/* Tabla local: filtros, selección, grupos, paginación y CSV. Conserva la fuente. */
(()=>{'use strict';const instances=new WeakMap(),normal=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 function init(root=document){return [...(root.matches?.('[data-explorador]')?[root]:[]),...root.querySelectorAll('[data-explorador]')].map(el=>{
  if(instances.has(el))return instances.get(el);
  const form=el.querySelector('form'),table=el.querySelector('table'),status=el.querySelector('[data-explorador-estado]'),initial=table?.tBodies[0],rows=[...(initial?.rows||[])],headers=[...(table?.tHead?.rows[0]?.cells||[])];
  if(!form||!status||!rows.length||!headers.length||headers.length>16||rows.length>2000||rows.some(r=>r.cells.length!==headers.length))return null;
  const abort=new AbortController(),listen=(node,type,fn)=>node.addEventListener(type,fn,{signal:abort.signal}),make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;},button=(label,fn)=>{const b=make('button',label);b.type='button';listen(b,'click',fn);return b;};
  const names=headers.map(h=>(h.querySelector('summary')||h).textContent.replace(/[↕↑↓]/g,'').trim()),values=rows.map(r=>[...r.cells].map(c=>c.textContent.trim())),raw=rows.map(r=>[...r.cells].map(c=>c.dataset.valor??c.textContent.trim()));
  const types=headers.map((h,c)=>h.dataset.tipo|| (rows.every(r=>r.cells[c].hasAttribute('data-valor'))?'numero':'texto'));
  if(types.some(t=>!['texto','numero','fecha'].includes(t))||raw.some(row=>row.some((v,c)=>types[c]==='numero'&&(!v||!Number.isFinite(Number(v))||Math.abs(Number(v))>1e12)||types[c]==='fecha'&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v))))return null;
  const previous={status:status.textContent,sort:headers.map(h=>h.getAttribute('aria-sort')),hidden:rows.map(r=>[...r.cells].map(c=>c.hidden)),headers:headers.map(h=>h.hidden)},parts=[],selected=new Set(),collapsed=new Set();let sorts=[{col:0,dir:1}],page=0,visible=[],pageRows=[],destroyed=false,renderAbort=new AbortController();
  const tools=make('div');tools.className='explorador-utilidades';const advanced=make('details'),summary=make('summary','Filtrar columna');advanced.className='control-menu';const panel=make('div');panel.className='control-panel';panel.tabIndex=0;panel.setAttribute('role','region');panel.setAttribute('aria-label','Filtro por columna');
  const field=make('select'),match=make('input'),min=make('input'),max=make('input');field.setAttribute('aria-label','Columna a filtrar');field.append(make('option','Todas'));field.firstChild.value='';names.forEach((n,c)=>{const o=make('option',n);o.value=c;field.append(o);});match.placeholder='Contiene…';match.setAttribute('aria-label','Texto del filtro');min.type=max.type='number';min.placeholder='Desde';max.placeholder='Hasta';min.setAttribute('aria-label','Valor mínimo');max.setAttribute('aria-label','Valor máximo');min.hidden=max.hidden=true;panel.append(field,match,min,max);advanced.append(summary,panel);
  const density=make('select');density.setAttribute('aria-label','Densidad de filas');for(const [v,n] of [['normal','Espaciado cómodo'],['compacta','Espaciado compacto']]){const o=make('option',n);o.value=v;density.append(o);}
  const selectAll=make('input');selectAll.type='checkbox';selectAll.setAttribute('aria-label','Seleccionar filas de esta página');const selectionLabel=make('label','Seleccionar página ');selectionLabel.prepend(selectAll);
  const selectedCount=make('span',''),csv=button('Exportar CSV',()=>downloadCSV()),clear=button('Limpiar selección',()=>{selected.clear();update();});tools.append(advanced,density,selectionLabel,selectedCount,clear,csv);form.after(tools);window.NotaControles?.init(tools);
  const footer=make('div');footer.className='explorador-paginacion';const prev=button('←',()=>{page--;update();}),next=button('→',()=>{page++;update();}),pageStatus=make('span'),size=make('select');prev.setAttribute('aria-label','Página anterior de tabla');next.setAttribute('aria-label','Página siguiente de tabla');size.setAttribute('aria-label','Filas por página');for(const n of [10,25,50,100]){const o=make('option',n+' filas');o.value=n;size.append(o);}size.value=String([10,25,50,100].includes(Number(el.dataset.paginaTamano))?Number(el.dataset.paginaTamano):25);footer.append(pageStatus,prev,next,size);el.querySelector('.tabla-caja').after(footer);
  const boxes=rows.map((r,i)=>{const c=make('input');c.type='checkbox';c.className='explorador-seleccion';c.setAttribute('aria-label','Seleccionar '+values[i][0]);r.cells[0].prepend(c);listen(c,'change',()=>{c.checked?selected.add(i):selected.delete(i);update();});return c;});
  const colValue=(i,c)=>types[c]==='numero'?Number(raw[i][c]):types[c]==='fecha'?Date.parse(raw[i][c]):values[i][c];
  function update(){if(destroyed)return;renderAbort.abort();renderAbort=new AbortController();parts.splice(0).forEach(p=>p.remove());initial.remove();rows.forEach(r=>r.hidden=false);
   const words=normal(form.elements.buscar?.value||'').trim().split(/\s+/),state=form.elements.estado?.value||'',group=form.elements.grupo?.value||'',fc=field.value===''?null:Number(field.value),numeric=fc!==null&&types[fc]!=='texto';min.hidden=max.hidden=!numeric;match.hidden=numeric;
   min.type=max.type=fc!==null&&types[fc]==='fecha'?'date':'number';const stateCol=Number(el.dataset.columnaEstado??2),groupCol=group===''?null:Number(group);
   visible=rows.map((r,i)=>i).filter(i=>(!state||values[i][stateCol]===state)&&words.every(w=>normal(values[i].join(' ')).includes(w))&&(numeric?(min.value===''||colValue(i,fc)>=(types[fc]==='fecha'?Date.parse(min.value):Number(min.value)))&&(max.value===''||colValue(i,fc)<=(types[fc]==='fecha'?Date.parse(max.value):Number(max.value))):normal(fc===null?values[i].join(' '):values[i][fc]).includes(normal(match.value))));
   visible.sort((a,b)=>{for(const s of sorts){const av=colValue(a,s.col),bv=colValue(b,s.col),c=types[s.col]==='texto'?av.localeCompare(bv,'es',{numeric:true,sensitivity:'base'}):av-bv;if(c)return s.dir*c;}return a-b;});
   const pages=Math.max(1,Math.ceil(visible.length/Number(size.value)));page=Math.max(0,Math.min(page,pages-1));pageRows=visible.slice(page*Number(size.value),(page+1)*Number(size.value));
   const hidden=new Set([...form.querySelectorAll('[data-columna]:not(:checked)')].map(e=>Number(e.dataset.columna)));if(hidden.size>=headers.length){hidden.delete(0);const box=form.querySelector('[data-columna="0"]');if(box)box.checked=true;}
   headers.forEach((h,c)=>h.hidden=hidden.has(c));rows.forEach((r,i)=>{[...r.cells].forEach((c,j)=>c.hidden=hidden.has(j));r.setAttribute('aria-selected',String(selected.has(i)));boxes[i].checked=selected.has(i);});
   const groups=new Map();pageRows.forEach(i=>{const key=groupCol===null?'':values[i][groupCol]??'';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(i);});
   if(!visible.length){const body=make('tbody'),tr=body.insertRow(),td=tr.insertCell();td.colSpan=headers.length-hidden.size;td.textContent='No hay resultados. Limpia los filtros para volver a ver los registros.';table.append(body);parts.push(body);}
   for(const [name,items] of groups){const body=make('tbody');if(groupCol!==null){const tr=body.insertRow(),th=make('th');th.scope='rowgroup';th.colSpan=headers.length-hidden.size;th.className='tabla-grupo';const b=make('button',(collapsed.has(name)?'▸ ':'▾ ')+name+' · '+items.length+' en esta página');b.type='button';b.addEventListener('click',()=>{collapsed.has(name)?collapsed.delete(name):collapsed.add(name);update();},{signal:renderAbort.signal});b.setAttribute('aria-expanded',String(!collapsed.has(name)));th.append(b);tr.append(th);}items.forEach(i=>{rows[i].hidden=groupCol!==null&&collapsed.has(name);body.append(rows[i]);});table.append(body);parts.push(body);}
   const totalCol=Number(el.dataset.columnaTotal??3),hasTotal=types[totalCol]==='numero',total=hasTotal?visible.reduce((n,i)=>n+Number(raw[i][totalCol]),0):0;
   status.textContent=visible.length+' de '+rows.length+' registros'+(hasTotal?' · '+total.toLocaleString('es-CO')+' '+(el.dataset.unidad||'COP')+' en la vista filtrada.':'.')+(sorts.length>1?' Orden: '+sorts.map(s=>names[s.col]).join(' → '):'');
   headers.forEach((h,c)=>{const s=sorts.find(s=>s.col===c);h.setAttribute('aria-sort',sorts[0]?.col===c?(sorts[0].dir===1?'ascending':'descending'):'none');const hint=h.querySelector('[data-indicador-orden]');if(hint)hint.textContent=s?(s.dir===1?'↑':'↓'):'↕';});
   selectedCount.textContent=selected.size+' seleccionados';clear.disabled=!selected.size;csv.textContent=selected.size?'Exportar selección ('+selected.size+')':'Exportar vista';selectAll.checked=!!pageRows.length&&pageRows.every(i=>selected.has(i));selectAll.indeterminate=pageRows.some(i=>selected.has(i))&&!selectAll.checked;
   pageStatus.textContent='Página '+(page+1)+' de '+pages;prev.disabled=page===0;next.disabled=page===pages-1;const count=form.querySelector('[data-filtros-cuenta]');if(count)count.textContent=state?'1 · ':'';
  }
  function exportCSV(){const indices=selected.size?rows.map((_,i)=>i).filter(i=>selected.has(i)):visible;const columns=headers.map((_,i)=>i).filter(c=>!headers[c].hidden);const safe=(v,numeric=false)=>'"'+(!numeric&&/^[\s]*[=+@\-]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';return [columns.map(c=>safe(names[c])).join(','),...indices.map(i=>columns.map(c=>safe(types[c]==='numero'?String(Number(raw[i][c])):values[i][c],types[c]==='numero')).join(','))].join('\r\n');}
  function downloadCSV(){const url=URL.createObjectURL(new Blob(['\ufeff'+exportCSV()],{type:'text/csv;charset=utf-8'})),a=make('a');a.href=url;a.download='tabla.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const resetPage=()=>{page=0;collapsed.clear();update();};listen(form,'input',resetPage);listen(form,'change',resetPage);listen(form,'submit',e=>e.preventDefault());listen(form,'reset',()=>queueMicrotask(()=>{if(destroyed)return;sorts=[{col:0,dir:1}];field.value=match.value=min.value=max.value='';resetPage();}));
  for(const input of [field,match,min,max,size])listen(input,'input',resetPage);listen(field,'change',()=>{match.value=min.value=max.value='';resetPage();});listen(density,'change',()=>el.dataset.densidad=density.value);listen(selectAll,'change',()=>{pageRows.forEach(i=>selectAll.checked?selected.add(i):selected.delete(i));update();});
  el.querySelectorAll('[data-orden-col]').forEach(b=>listen(b,'click',e=>{const c=Number(b.dataset.ordenCol),requested=Number(b.dataset.direccion)||0,dir=b.parentElement===headers[c]&&sorts[0]?.col===c?-sorts[0].dir:requested;if(c<0||c>=headers.length)return;sorts=dir===0?[]:e.shiftKey?[...sorts.filter(s=>s.col!==c),{col:c,dir}]:[{col:c,dir}];resetPage();}));
  listen(window,'beforeprint',()=>{parts.splice(0).forEach(p=>p.remove());headers.forEach(h=>h.hidden=false);rows.forEach(r=>{r.hidden=false;[...r.cells].forEach(c=>c.hidden=false);initial.append(r);});table.append(initial);});listen(window,'afterprint',update);
  const instance={update,exportCSV,get selected(){return [...selected].map(i=>values[i]);},get visible(){return visible.map(i=>values[i]);},destroy(){destroyed=true;abort.abort();renderAbort.abort();parts.forEach(p=>p.remove());boxes.forEach(b=>b.remove());rows.forEach((r,i)=>{r.hidden=false;r.removeAttribute('aria-selected');[...r.cells].forEach((c,j)=>c.hidden=previous.hidden[i][j]);initial.append(r);});headers.forEach((h,i)=>{h.hidden=previous.headers[i];previous.sort[i]===null?h.removeAttribute('aria-sort'):h.setAttribute('aria-sort',previous.sort[i]);});table.append(initial);tools.querySelectorAll('.control-menu').forEach(m=>window.NotaControles?.get(m)?.destroy());tools.remove();footer.remove();delete el.dataset.densidad;status.textContent=previous.status;instances.delete(el);}};instances.set(el,instance);update();return instance;
 });}window.NotaExplorador={init,get:el=>instances.get(el)};init();
})();
