/* Revisión v2: eventos inmutables por documento. Identidad declarada, sin servidor. */
(()=>{'use strict';
 const text=(v,max)=>typeof v==='string'&&v.length<=max;
 const uid=()=>globalThis.crypto.randomUUID();
 function validate(e){
  if(!e||!text(e.id,80)||!e.id||!text(e.thread,80)||!e.thread||!Number.isSafeInteger(e.time)||e.time<0||!text(e.author,80)||!e.author||!['create','reply','edit','resolve','delete','assign'].includes(e.kind))throw Error('Evento de revisión inválido.');
  if(['create','reply','edit'].includes(e.kind)&&(!text(e.text,4000)||!e.text.trim()))throw Error('Texto de comentario inválido.');
  if(e.kind==='resolve'&&typeof e.resolved!=='boolean')throw Error('Estado inválido.');
  if(e.kind==='assign'&&!text(e.assignee,80))throw Error('Responsable inválido.');
  if(e.kind==='create'){if(e.entry_type!==undefined&&!['comment','note'].includes(e.entry_type))throw Error('Tipo inválido.');if(e.session!==undefined&&!text(e.session,200))throw Error('Sesión demasiado larga.');const a=e.anchor;if(!a||!text(a.reference,200)||!text(a.tag,20)||!text(a.text,4000)||!text(a.quote,1200)||!text(a.page,300)||![a.x,a.y].every(v=>Number.isFinite(v)&&v>=0&&v<=1))throw Error('Contexto de comentario inválido.');}
  return e;
 }
 function create(documentId,storage){
  if(!text(documentId,1000)||!documentId)throw Error('Documento inválido.');
  const prefix='nota-revision-v2:'+encodeURIComponent(documentId)+':';let events=new Map(),persistent=!!storage,lastTime=0;
  function read(){if(!storage)return;try{for(let i=0;i<storage.length;i++){const key=storage.key(i);if(!key?.startsWith(prefix))continue;try{const e=validate(JSON.parse(storage.getItem(key)));if(key!==prefix+e.id)continue;events.set(e.id,e);lastTime=Math.max(lastTime,e.time);}catch{}}}catch{persistent=false;}}
  read();
  function append(kind,thread,author,data={}){read();if(events.size>=2000)throw Error('La revisión alcanzó 2000 eventos. Exporta antes de comenzar otra revisión.');const e=validate({...data,id:uid(),thread:thread||uid(),kind,author:author.trim()||'Sin nombre',time:Math.max(Date.now(),lastTime+1)});if(storage)try{storage.setItem(prefix+e.id,JSON.stringify(e));}catch{persistent=false;}events.set(e.id,e);lastTime=e.time;return e;}
  function state(){read();const ordered=[...events.values()].sort((a,b)=>a.time-b.time||a.id.localeCompare(b.id)),threads=new Map();for(const e of ordered.filter(e=>e.kind==='create'))if(!threads.has(e.thread))threads.set(e.thread,{id:e.thread,text:e.text,author:e.author,anchor:e.anchor,entry_type:e.entry_type||'comment',session:e.session||'',version:e.version||'',resolved:false,deleted:false,assignee:'',replies:[],time:e.time,history:[]});for(const e of ordered){const t=threads.get(e.thread);if(!t)continue;t.history.push(e);if(e.kind==='edit')t.text=e.text;if(e.kind==='reply')t.replies.push(e);if(e.kind==='resolve')t.resolved=e.resolved;if(e.kind==='assign')t.assignee=e.assignee;if(e.kind==='delete')t.deleted=true;}return [...threads.values()].filter(t=>!t.deleted);}
  function exportData(){read();return {format:'nota-revision',version:2,document:documentId,events:[...events.values()].sort((a,b)=>a.time-b.time||a.id.localeCompare(b.id))};}
  function importData(value){if(!value||value.format!=='nota-revision'||value.version!==2||value.document!==documentId||!Array.isArray(value.events)||value.events.length>2000)throw Error('El archivo no corresponde a esta revisión o tiene un formato inválido.');read();const merged=new Map(events);for(const raw of value.events){const e=validate(raw);if(merged.has(e.id)&&JSON.stringify(merged.get(e.id))!==JSON.stringify(e))throw Error('Conflicto de identificador: conserva ambos archivos para revisarlos.');merged.set(e.id,e);}if(merged.size>2000)throw Error('La revisión excede 2000 eventos.');const threads=new Set([...merged.values()].filter(e=>e.kind==='create').map(e=>e.thread));if([...merged.values()].some(e=>!threads.has(e.thread)))throw Error('Hay respuestas sin hilo original.');const added=[...merged.values()].filter(e=>!events.has(e.id));if(storage){const written=[];try{for(const e of added){storage.setItem(prefix+e.id,JSON.stringify(e));written.push(prefix+e.id);}}catch{written.forEach(k=>storage.removeItem(k));throw Error('No hay espacio local para importar. Exporta tu revisión antes de continuar.');}}events=merged;lastTime=Math.max(lastTime,...added.map(e=>e.time));return added.length;}
  return {append,state,exportData,importData,read,prefix,get persistent(){return persistent;}};
 }
 globalThis.NotaRevisionStore={create,validate};
})();

/* Comentarios locales: pines flotantes anclados al bloque, sin mutar su geometría. */
(()=>{'use strict';const instances=new WeakMap();
 const icon='<svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M20 11.5a8 8 0 0 1-8 8H5l-3 3V11.5a9 9 0 0 1 18 0Z" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>';
 function init(root=document){return [...(root.matches?.('[data-revision]')?[root]:[]),...root.querySelectorAll('[data-revision]')].map(el=>{
  if(instances.has(el))return instances.get(el);
  const editor=el.querySelector('[data-revision-editor]'),panel=el.querySelector('[data-revision-panel]'),input=el.querySelector('[data-revision-texto]'),context=el.querySelector('[data-revision-contexto]'),list=el.querySelector('[data-revision-notas]'),prompt=el.querySelector('[data-revision-prompt]'),status=el.querySelector('[data-revision-estado]');
  if(!editor||!panel||!input||!context||!list||!prompt||!status)return null;
  const originalEditor=editor.innerHTML;
  const abort=new AbortController(),notes=[],addedIDs=new Set(),originalStatus=status.textContent,originalPrompt=prompt.textContent,focusTargets=new Map();let pinScope=null;let rowsAbort=new AbortController(),mode=false,pending=null,editing=null,serial=0;
  const bar=document.createElement('div'),layer=document.createElement('div');bar.className='revision-barra revision-ui';bar.setAttribute('role','group');bar.setAttribute('aria-label','Comentarios');layer.className='revision-capa revision-ui';
  const modeButton=el.querySelector('[data-revision-modo]').cloneNode(true),listButton=el.querySelector('[data-revision-lista]').cloneNode(true);modeButton.innerHTML=icon;modeButton.setAttribute('aria-label','Comentar: activar pines');modeButton.title='Comentar';listButton.textContent='0';listButton.title='Ver comentarios';listButton.setAttribute('aria-label','Ver comentarios, 0');bar.append(modeButton,listButton);document.body.append(bar,layer,editor,panel);
  const listen=(node,type,fn,options={})=>node.addEventListener(type,fn,{...options,signal:abort.signal}),make=(tag,text)=>{const node=document.createElement(tag);node.textContent=text;return node;};
  const documentId=document.querySelector('meta[name="nota-documento"]')?.content||(document.querySelector('meta[name="nota-titulo-anterior"]')?.content||document.title)+'@'+location.pathname;
  const bridge=globalThis.BottifactReviewBridge;let remote=null,unsubscribe=null,saving=false;
  let storage;if(!bridge)try{storage=localStorage;}catch{}let store=NotaRevisionStore.create(documentId,storage);
  let author='';try{author=storage?.getItem('nota-revision-autor')||'';}catch{}
  panel.classList.add('revision-panel-v2');panel.querySelector('h2').textContent='Comentarios y notas';const toolbar=make('div','');toolbar.className='revision-utilidades';
  const authorLabel=make('label','Tu nombre'),authorInput=make('input','');authorInput.placeholder='Nombre para esta revisión';authorInput.maxLength=80;authorInput.value=author;authorLabel.append(authorInput);
  const filterLabel=make('label','Mostrar'),filter=make('select','');for(const [value,label] of [['open','Abiertos'],['all','Todos'],['resolved','Resueltos'],['mine','Asignados a mí']]){const o=make('option',label);o.value=value;filter.append(o);}filterLabel.append(filter);
  const exportButton=make('button','Exportar revisión'),importLabel=make('label','Importar revisión'),importInput=make('input','');exportButton.type='button';importInput.type='file';importInput.className='sr-only';importInput.accept='.json,application/json';importLabel.className='revision-importar';importLabel.append(importInput);
  const promptPre=prompt.closest('pre'),promptContainer=promptPre.parentElement,promptDetails=make('details','');promptDetails.className='revision-prompt-detalle';promptDetails.append(make('summary','Ver texto completo'),promptPre);promptContainer.append(promptDetails);
  const feedback=make('p','');feedback.className='revision-guardado';feedback.setAttribute('role','status');const allPins=make('button','Ver todos los comentarios');allPins.type='button';allPins.hidden=true;listen(allPins,'click',()=>{pinScope=null;render();});toolbar.append(allPins,authorLabel,filterLabel,exportButton,importLabel,feedback);list.before(toolbar);
  const typeLabel=make('label','Tipo'),type=make('select','');typeLabel.className='revision-field';type.setAttribute('aria-label','Visibilidad del comentario');for(const [value,label] of [['comment','Comentario compartido'],['note','Nota privada · sólo yo']]){const option=make('option',label);option.value=value;type.append(option);}typeLabel.append(type);editor.querySelector('form').insertBefore(typeLabel,input);listen(type,'change',()=>{editor.querySelector('h2').textContent=type.value==='note'?'Nota privada':'Comentario';editor.querySelector('[data-revision-guardar]').setAttribute('aria-label',type.value==='note'?'Guardar nota':'Guardar comentario');});const sessionDetails=make('details',''),sessionInput=make('input','');sessionDetails.className='revision-session';sessionDetails.append(make('summary','Sesión o encargo (opcional)'));sessionInput.maxLength=200;sessionInput.setAttribute('aria-label','Sesión o encargo');sessionInput.placeholder='Referencia para retomar con la IA';sessionDetails.append(sessionInput);input.after(sessionDetails);if(!bridge){type.options[0].textContent='Comentario local';type.options[1].textContent='Nota local';}
  const noteButton=make('button','✎');noteButton.type='button';noteButton.title='Añadir nota privada';noteButton.setAttribute('aria-label','Añadir nota privada');bar.insertBefore(noteButton,listButton);let choosingType='comment';listen(noteButton,'click',()=>{choosingType='note';toggle();});
  // Compact composer: the writing surface stays primary; metadata is disclosed on demand.
  const composerForm=editor.querySelector('form'),composerTitle=editor.querySelector('h2'),composerActions=editor.querySelector('.acciones'),composerContext=editor.querySelector('.revision-contexto');
  const composerError=make('p','');composerError.className='review-composer-error';composerError.setAttribute('role','alert');composerError.hidden=true;input.after(composerError);
  const composerHeader=make('div',''),composerAvatar=make('span',''),composerName=make('span',''),composerPrivacy=make('span','');
  composerHeader.className='review-composer-header';composerAvatar.className='review-composer-avatar';composerAvatar.setAttribute('aria-hidden','true');composerName.className='review-composer-name';composerPrivacy.className='review-composer-privacy';
  const composerCancel=editor.querySelector('[data-revision-cancelar]');composerCancel.title='Cerrar comentario';composerCancel.setAttribute('aria-label','Cerrar comentario');
  composerHeader.append(composerAvatar,composerName,composerCancel);composerForm.prepend(composerHeader);composerTitle.classList.add('sr-only');
  const composerOptions=make('details',''),composerSummary=make('summary',''),composerMetadata=make('div','');composerOptions.className='review-composer-options';composerSummary.setAttribute('aria-label','Contexto y opciones');composerSummary.title='Contexto y opciones';composerSummary.append(window.BottifactUI?.icon('more')||make('span','…'));composerOptions.append(composerSummary,composerMetadata);composerMetadata.className='review-composer-metadata';
  composerMetadata.append(sessionDetails);if(composerContext)composerMetadata.prepend(composerContext);
  const composerFooter=make('div','');composerFooter.className='review-composer-footer';typeLabel.classList.add('review-privacy');typeLabel.firstChild.textContent='';type.options[0].textContent=bridge?'Compartido':'Comentario local';type.options[1].textContent=bridge?'Privado · solo yo':'Nota local';composerFooter.append(typeLabel,composerOptions,composerActions);composerPrivacy.hidden=true;composerForm.append(composerFooter);editor.classList.add('review-composer');
  const composerSubmit=editor.querySelector('[data-revision-guardar]');composerSubmit.title='Enviar · ⌘/Ctrl + Enter';
  function refreshComposer(){const label=authorInput.value.trim()||'Tu comentario';composerName.textContent=label;composerAvatar.textContent=label.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();composerPrivacy.textContent=type.value==='note'?(bridge?'Sólo tú':'Nota local'):(bridge?'Comentario':'Comentario local');input.placeholder=type.value==='note'?'Escribe una nota…':'Escribe un comentario…';}
  listen(type,'change',refreshComposer);listen(composerOptions,'toggle',position);listen(document,'pointerdown',e=>{if(composerOptions.open&&!composerOptions.contains(e.target))composerOptions.open=false;});refreshComposer();
  const copyAll=make('button','Copiar todo para IA'),copyOpen=make('button','Copiar pendientes');copyAll.type=copyOpen.type='button';toolbar.append(copyAll,copyOpen);for(const [button,scope] of [[copyAll,'all'],[copyOpen,'open']])listen(button,'click',async()=>{if(bridge){try{await bridge.exportPrompt(scope);}catch(error){feedback.textContent=error.message;}}else{const selected=notes.filter(n=>scope==='all'||!n.resolved),text=localPrompt(selected);try{await navigator.clipboard.writeText(text);feedback.textContent='Prompt copiado.';}catch{prompt.textContent=text;promptDetails.open=true;prompt.scrollIntoView({block:'center'});feedback.textContent='Selecciona el texto del prompt para copiarlo.';}}});
  function localPrompt(selected){return 'Revisión de «'+document.title+'»\nDocumento: '+documentId+'\n'+(remote?.artifact?.url||location.href)+'\nConserva el documento-id y verifica el contexto antes de editar.\n\n'+selected.map(n=>'Tipo: '+(n.entry_type==='note'?'nota personal':'comentario')+'\nAutor: '+n.author+'\nVersión: '+(n.version||'archivo local')+'\nSesión: '+(n.session||'no registrada')+'\nSección: '+(n.anchor.section||n.page)+' / #'+n.reference+'\nContexto completo: '+n.blockText+'\nCita: '+n.quote+'\nAjuste: '+n.text+'\nRespuestas: '+n.replies.map(r=>r.author+': '+r.text).join(' | ')).join('\n\n');}
  if(bridge){authorInput.readOnly=true;importInput.disabled=true;importLabel.hidden=true;authorInput.placeholder='Identidad del portal';}
  const semanticText=node=>{const copy=node.cloneNode(true);copy.querySelectorAll('[aria-hidden="true"],.revision-ui').forEach(n=>n.remove());return copy.textContent.trim().replace(/\s+/g,' ').slice(0,4000);};
  function findTarget(anchor){const base=document.getElementById(anchor.reference)||document.querySelector('main');if(!base)return null;const candidates=[base,...base.querySelectorAll('p,h1,h2,h3,h4,figure,pre,li,table,section,button,a,input,select,textarea')].filter(n=>n.tagName===anchor.tag&&semanticText(n)===anchor.text&&!n.closest('[data-revision],.revision-ui'));return candidates.length===1?candidates[0]:null;}
  function hydrate(){const old=new Map(notes.map(n=>[n.id,n]));notes.splice(0);for(const t of store.state()){const previous=old.get(t.id),target=previous?.target?.isConnected?previous.target:findTarget(t.anchor),n={...t,...t.anchor,text:t.text,blockText:t.anchor.text,target,marker:previous?.marker||make('button','')};if(target&&!target.id){let id;do{id='nota-revision-bloque-'+(++serial);}while(document.getElementById(id));target.id=id;addedIDs.add(target);}n.marker.type='button';n.marker.className='revision-marca';n.marker.dataset.kind=n.entry_type;n.marker.onclick=()=>{if(n.marker._pinGroup?.length>1){pinScope=new Set(n.marker._pinGroup);filter.value='all';render();panel.showModal();return;}if(n.target&&(!bridge||((remote?.permissions.comment||n.entry_type==='note')&&(remote.permissions.edit||n.history[0]?.actor===remote.actor))))open(n);else{filter.value='all';render();panel.showModal();}};layer.append(n.marker);notes.push(n);old.delete(t.id);}old.forEach(n=>n.marker.remove());render();}
  async function mutate(kind,n,data={}){try{if(bridge){const result=await bridge.commit({kind,thread:n?.id,...data});store.importData(result.snapshot);}else store.append(kind,n?.id,authorInput.value.trim()||'Sin nombre',data);hydrate();return true;}catch(e){feedback.textContent=e.message;status.textContent=e.message;composerError.textContent=e.message;composerError.hidden=false;return false;}}
  listen(authorInput,'change',()=>{author=authorInput.value.trim();try{storage?.setItem('nota-revision-autor',author);}catch{}render();});listen(filter,'change',render);
  listen(window,'storage',e=>{if(e.key?.startsWith(store.prefix))hydrate();});
  function download(value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=make('a','');a.href=url;a.download='revision-nota.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  listen(exportButton,'click',()=>download(store.exportData()));listen(importInput,'change',async()=>{const file=importInput.files[0];if(!file)return;try{if(file.size>2000000)throw Error('El archivo supera 2 MB.');const count=store.importData(JSON.parse(await file.text()));hydrate();feedback.textContent=count+' eventos incorporados. Los duplicados se omiten.';}catch(e){feedback.textContent=e.message;}finally{importInput.value='';}});
  function setMode(value){focusTargets.forEach((old,node)=>old===null?node.removeAttribute('tabindex'):node.setAttribute('tabindex',old));focusTargets.clear();
   if(value)document.querySelectorAll('main .pagina.viva :is(p,h1,h2,h3,figure,pre),main:not(.multipagina) :is(p,h1,h2,h3,figure,pre)').forEach(node=>{if(node.closest('[data-revision],.revision-ui')||!node.getClientRects().length)return;focusTargets.set(node,node.getAttribute('tabindex'));node.tabIndex=0;});
   mode=value;document.dispatchEvent(new CustomEvent('bottifact:review-mode',{detail:{active:mode,kind:choosingType}}));document.documentElement.toggleAttribute('data-revisando',mode);modeButton.setAttribute('aria-pressed',String(mode));el.querySelector('[data-revision-modo]').setAttribute('aria-pressed',String(mode));modeButton.setAttribute('aria-label',mode?'Comentar: elige un punto. Escape cancela.':'Comentar: activar pines');status.textContent=mode?'Haz clic donde quieras comentar. Tab y Enter también permiten elegir un bloque.':notes.length+' comentarios · '+(bridge?'revisión compartida.':store.persistent?'guardados en este navegador.':'en memoria: exporta antes de cerrar.');
  }
  function point(note){const r=note.target?.getBoundingClientRect()||{left:innerWidth/2,top:innerHeight/3,width:0,height:0};return {x:r.left+r.width*note.x,y:r.top+r.height*note.y,r};}
  function position(){
   const vw=visualViewport?.width||innerWidth,vh=visualViewport?.height||innerHeight,ox=visualViewport?.offsetLeft||0,oy=visualViewport?.offsetTop||0;
   const pinGroups=[];notes.forEach(note=>{note.marker._pinGroup=null;const p=point(note);let visible=!!note.target&&!note.resolved&&note.target.getClientRects().length>0&&p.x>=ox&&p.x<=ox+vw&&p.y>=oy+54&&p.y<=oy+vh;
    for(let a=note.target?.parentElement;a&&a!==document.body;a=a.parentElement){const s=getComputedStyle(a);if(/auto|scroll|hidden|clip/.test(s.overflowX+' '+s.overflowY)){const r=a.getBoundingClientRect();if(p.x<r.left||p.x>r.right||p.y<r.top||p.y>r.bottom)visible=false;}}
    note.marker.hidden=!visible;note.marker.style.left=Math.max(ox+4,Math.min(ox+vw-32,p.x-4))+'px';note.marker.style.top=Math.max(oy+4,Math.min(oy+vh-36,p.y-28))+'px';if(visible){const x=parseFloat(note.marker.style.left),y=parseFloat(note.marker.style.top),group=pinGroups.find(g=>Math.hypot(g.x-x,g.y-y)<36);if(group){group.notes.push(note);note.marker.hidden=true;}else pinGroups.push({x,y,notes:[note]});}
   });
   pinGroups.forEach(g=>{const first=g.notes[0],label=g.notes.length+' '+(g.notes.length===1?'comentario':'comentarios')+' en este punto';first.marker._pinGroup=g.notes.map(n=>n.id);first.marker.textContent=String(g.notes.length);first.marker.dataset.count=String(g.notes.length);first.marker.setAttribute('aria-label',label+': '+g.notes.map(n=>n.text.slice(0,60)).join(' · '));first.marker.title=label;});
   if(editor.open&&pending){const p=point(pending);editor.style.width=Math.min(340,vw-24)+'px';editor.style.maxHeight=Math.max(160,vh-24)+'px';const r=editor.getBoundingClientRect();editor.style.left=Math.max(ox+12,Math.min(p.x+14,ox+vw-r.width-12))+'px';editor.style.top=Math.max(oy+12,Math.min(p.y+12,oy+vh-r.height-12))+'px';if(pending.target&&!pending.target.getClientRects().length)editor.close();}
   if(editor.open&&composerOptions.open){const a=composerSummary.getBoundingClientRect();composerMetadata.style.width=Math.min(300,vw-24)+'px';composerMetadata.style.maxHeight=Math.max(80,vh-24)+'px';const r=composerMetadata.getBoundingClientRect();composerMetadata.style.left=Math.max(ox+12,Math.min(a.right-r.width,ox+vw-r.width-12))+'px';composerMetadata.style.top=Math.max(oy+12,Math.min(a.top-r.height-8,oy+vh-r.height-12))+'px';}
  }
  function render(){rowsAbort.abort();rowsAbort=new AbortController();list.replaceChildren();const on=(n,fn)=>n.addEventListener('click',fn,{signal:rowsAbort.signal});
   allPins.hidden=!pinScope;const shown=notes.filter(n=>!pinScope||pinScope.has(n.id)).filter(n=>filter.value==='all'||filter.value==='open'&&!n.resolved||filter.value==='resolved'&&n.resolved||filter.value==='mine'&&!!authorInput.value.trim()&&n.assignee===authorInput.value.trim());
   notes.forEach((note,i)=>{note.marker.textContent=String(i+1);note.marker.setAttribute('aria-label','Comentario '+(i+1)+': '+note.text.slice(0,80));});
   shown.forEach(note=>{const li=make('li',''),actions=make('div','');li.className='revision-hilo';li.dataset.thread=note.id;actions.className='acciones';
    const meta=make('p',(note.entry_type==='note'?'Nota privada · ':'')+note.author+(bridge?(note.history[0]?.verified?' · correo verificado':' · invitado'):'')+' · '+new Date(note.time).toLocaleDateString('es')+' · '+(note.resolved?'Resuelto':'Abierto'));meta.className='revision-meta';
    const details=make('details','');details.append(make('summary',note.page+' · #'+note.reference),make('blockquote',note.quote));
    if(note.target){const link=make('a','Ver contexto');link.href='#'+note.target.id;on(link,e=>{e.preventDefault();panel.close();const page=note.target.closest('.pagina');if(page?.hidden)document.querySelector('[data-ir="'+page.id+'"]')?.click();note.target.scrollIntoView({block:'center',behavior:'instant'});});actions.append(link);}else details.append(make('p','El bloque cambió o falta. Revisa la cita original antes de aplicar el ajuste.'));
    for(const [title,fn] of [['Editar',()=>{panel.close();open(note);}], [note.resolved?'Reabrir':'Resolver',()=>mutate('resolve',note,{resolved:!note.resolved})],['Archivar',()=>mutate('delete',note)]]){if(bridge&&note.entry_type!=='note'&&(!remote?.permissions.comment||(!remote.permissions.edit&&(title!=='Editar'||note.history[0]?.actor!==remote.actor))))continue;const b=make('button',title);b.type='button';on(b,fn);actions.append(b);}
    li.append(meta,make('p',note.text),details);
    if(note.replies.length){const replies=make('ol','');replies.className='revision-respuestas';for(const reply of note.replies)replies.append(make('li',reply.author+': '+reply.text));li.append(replies);}
    const response=make('div',''),reply=make('input',''),send=make('button','Responder');response.className='revision-responder';reply.placeholder='Añadir una respuesta…';reply.maxLength=4000;reply.setAttribute('aria-label','Respuesta al comentario de '+note.author);send.type='button';on(send,()=>{if(reply.value.trim())mutate('reply',note,{text:reply.value.trim()});});response.append(reply,send);
    if(bridge&&!remote?.permissions.comment&&note.entry_type!=='note'){reply.disabled=true;send.disabled=true;}
    const assignLabel=make('label','Responsable'),assign=make('input','');assign.value=note.assignee;assign.maxLength=80;assign.placeholder='Sin asignar';assign.setAttribute('aria-label','Responsable del comentario de '+note.author);assign.readOnly=!!bridge&&!remote?.permissions.edit&&note.entry_type!=='note';assignLabel.append(assign);assign.addEventListener('change',()=>mutate('assign',note,{assignee:assign.value.trim()}),{signal:rowsAbort.signal});
    const history=make('details','');history.append(make('summary','Actividad · '+note.history.length));for(const e of note.history)history.append(make('p',e.author+' · '+e.kind+(e.text?' · '+e.text:'')));li.append(response,assignLabel,actions,history);list.append(li);
   });
   if(!shown.length)list.append(make('li',notes.length?'No hay comentarios en esta vista.':'Aún no hay comentarios. Activa el globo y elige un punto del documento.'));
   const active=notes.filter(n=>!n.resolved);prompt.textContent=localPrompt(active);
   document.dispatchEvent(new CustomEvent('bottifact:review-count',{detail:{open:active.length,total:notes.length}}));listButton.textContent=String(active.length);listButton.setAttribute('aria-label','Ver comentarios, '+active.length+' abiertos');status.textContent=notes.length+' comentarios · '+(bridge?'revisión compartida.':store.persistent?'guardados en este navegador.':'en memoria: exporta antes de cerrar.');feedback.textContent=bridge?'Comentarios guardados.':store.persistent?'Guardado local. Exportar incluye todo el historial, también los hilos archivados.':'Sin almacenamiento persistente. Exporta antes de cerrar.';panel.querySelector('.procedencia').textContent=bridge?'Revisión compartida. El portal verifica permisos e identifica los nombres declarados como invitados.':'Revisión local con historial. Los nombres son declarados; compartir requiere exportar e importar.';position();
  }
  function open(note){if(editor.open)editor.close();editing=notes.includes(note)?note:null;setMode(false);if(editing&&note.target){const page=note.target.closest('.pagina');if(page?.hidden)document.querySelector('[data-ir="'+page.id+'"]')?.click();const r=note.target.getBoundingClientRect();if(r.bottom<60||r.top>innerHeight-60)note.target.scrollIntoView({behavior:'instant',block:'center'});}pending=note;type.value=editing?note.entry_type:choosingType;type.disabled=!!editing;type.options[0].disabled=!!bridge&&!remote?.permissions.comment;type.options[1].disabled=!!bridge&&!remote?.verified;sessionInput.value=editing?note.session:'';sessionDetails.open=false;sessionInput.disabled=!!editing;context.textContent=note.page+' · #'+note.reference+' · '+note.quote;input.value=editing?note.text:'';editor.querySelector('h2').textContent=type.value==='note'?'Nota privada':editing?'Comentario '+(notes.indexOf(note)+1):'Comentario';editor.querySelector('[data-revision-guardar]').setAttribute('aria-label',type.value==='note'?'Guardar nota':'Guardar comentario');editor.querySelector('details').open=false;composerOptions.open=false;composerError.hidden=true;refreshComposer();editor.show();resizeInput();position();input.focus({preventScroll:true});}
  function choose(target,selection='',coords){if(!target?.closest('main')||target.closest('.revision-ui,[data-revision]'))return;
   const page=target.closest('.pagina');let anchor=target;while(anchor&&(!anchor.id||addedIDs.has(anchor)))anchor=anchor.parentElement;
   const semantic=target.cloneNode(true);semantic.querySelectorAll('[aria-hidden="true"]').forEach(n=>n.remove());
   const quote=(selection||semantic.textContent||target.getAttribute('aria-label')||target.labels?.[0]?.textContent||target.tagName).trim().replace(/\s+/g,' ').slice(0,1200),r=target.getBoundingClientRect();
   open({target,tag:target.tagName,blockText:semanticText(target),reference:anchor?.id||page?.id||'contenido',page:page?.querySelector('h1')?.textContent||document.title,section:target.closest('section')?.querySelector('h2,h3')?.textContent?.slice(0,300)||'',quote,text:'',x:coords&&r.width?Math.max(0,Math.min(1,(coords.x-r.left)/r.width)):.5,y:coords&&r.height?Math.max(0,Math.min(1,(coords.y-r.top)/r.height)):.5});
  }
  function toggle(){if(bridge&&remote&&!(choosingType==='note'?remote.verified:remote.permissions.comment)){if(!remote.author)bridge.identify();else status.textContent='Tu acceso a esta revisión es de lectura.';return;}if(editor.open)editor.close();const selection=getSelection(),text=selection?.toString().trim(),node=selection?.anchorNode;if(text&&node){const target=(node.nodeType===1?node:node.parentElement).closest('p,h1,h2,h3,h4,figure,pre,li');if(target?.closest('main')){choose(target,text);return;}}setMode(!mode);}
  [modeButton,el.querySelector('[data-revision-modo]')].forEach(b=>listen(b,'click',()=>{choosingType='comment';toggle();}));[listButton,el.querySelector('[data-revision-lista]')].forEach(b=>listen(b,'click',()=>{pinScope=null;setMode(false);editor.close();render();panel.showModal();}));
  listen(document,'click',e=>{if(!mode||e.target.closest('.revision-ui,[data-revision],.barra'))return;const target=e.target.closest('button,a,input,select,textarea,p,h1,h2,h3,h4,pre,figure,table,li,.card-editorial,section,.pagina');if(!target?.closest('main'))return;e.preventDefault();e.stopImmediatePropagation();choose(target,'',{x:e.clientX,y:e.clientY});},{capture:true});
  listen(document,'nota:pagina',()=>{setMode(false);editor.close();position();});listen(window,'scroll',position,{capture:true,passive:true});listen(window,'resize',position);if(window.visualViewport){listen(visualViewport,'resize',position);listen(visualViewport,'scroll',position);}
  const resize=new ResizeObserver(position);resize.observe(document.querySelector('main')||document.body);resize.observe(editor);
  listen(document,'keydown',e=>{if(mode&&e.key==='Enter'&&focusTargets.has(e.target)){e.preventDefault();choose(e.target);return;}if(e.key==='Escape'&&editor.open&&composerOptions.open){e.preventDefault();composerOptions.open=false;composerSummary.focus();return;}if(e.key==='Escape'&&(mode||editor.open)){e.preventDefault();setMode(false);editor.close();(document.querySelector('.bottifact-toolbar>button[aria-label="Comentar en un punto"]')||modeButton).focus();}});
  listen(editor.querySelector('form'),'submit',e=>{e.preventDefault();save();});
  function resizeInput(){input.style.height='auto';input.style.height=Math.min(160,Math.max(44,input.scrollHeight))+'px';editor.querySelector('[data-revision-guardar]').disabled=!input.value.trim();position();}
  async function save(){if(saving)return;if(!input.value.trim()){input.setCustomValidity('Escribe el comentario.');input.reportValidity();return;}input.setCustomValidity('');if(!input.reportValidity())return;
   if(!editing&&pending.target&&!pending.target.id){let id;do{id='nota-revision-bloque-'+(++serial);}while(document.getElementById(id));addedIDs.add(pending.target);pending.target.id=id;}
   const a=pending;const anchor={reference:a.reference,tag:a.tag,text:a.blockText,quote:a.quote,page:a.page.slice(0,300),section:a.section||a.anchor?.section||'',x:a.x,y:a.y};
   saving=true;let saved;try{saved=await mutate(editing?'edit':'create',editing,{text:input.value.trim(),...(editing?{}:{anchor,entry_type:type.value,session:sessionInput.value.trim()})});}finally{saving=false;}if(!saved)return;
   editor.close();pending=null;editing=null;(document.querySelector('.bottifact-toolbar>button[aria-label="Comentar en un punto"]')||modeButton).focus({preventScroll:true});
  }
  listen(editor.querySelector('[data-revision-guardar]'),'click',save);listen(input,'input',()=>{input.setCustomValidity('');resizeInput();});listen(input,'keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();save();}});listen(editor.querySelector('[data-revision-cancelar]'),'click',()=>{editor.close();(document.querySelector('.bottifact-toolbar>button[aria-label="Comentar en un punto"]')||modeButton).focus({preventScroll:true});});listen(panel.querySelector('[data-revision-cerrar]'),'click',()=>panel.close());
  listen(document,'bottifact:focus-thread',event=>{const note=notes.find(n=>n.id===event.detail);if(!note)return;filter.value='all';render();panel.showModal();const li=[...list.children].find(li=>li.dataset.thread===note.id);li?.scrollIntoView({block:'center'});li?.classList.add('revision-enfocado');});
  hydrate();if(bridge)unsubscribe=bridge.subscribe(value=>{try{remote=value;noteButton.hidden=!value.verified;copyAll.hidden=copyOpen.hidden=!value.verified;authorInput.value=value.author||'';store=NotaRevisionStore.create(documentId);store.importData(value.snapshot);hydrate();feedback.textContent='Comentarios guardados. '+(value.verified?'Identidad verificada.':'Nombre declarado.');status.textContent=notes.length+' comentarios · revisión compartida.';}catch(e){status.textContent=e.message;}});
  const instance={exportData:()=>store.exportData(),importData:value=>{if(bridge)throw Error('La importación de archivos locales al portal todavía no está disponible.');const count=store.importData(value);hydrate();return count;},get comments(){return notes.map(({id,text,quote,page,reference,x,y,resolved,replies,assignee})=>({id,text,quote,page,reference,x,y,resolved,replies,assignee}));},destroy(){unsubscribe?.();setMode(false);abort.abort();rowsAbort.abort();resize.disconnect();editor.close();panel.close();bar.remove();layer.remove();toolbar.remove();editor.innerHTML=originalEditor;editor.classList.remove('review-composer');promptContainer.append(promptPre);promptDetails.remove();panel.classList.remove('revision-panel-v2');addedIDs.forEach(n=>n.removeAttribute('id'));el.append(editor,panel);status.textContent=originalStatus;prompt.textContent=originalPrompt;list.replaceChildren();instances.delete(el);}};instances.set(el,instance);return instance;
 });}window.NotaRevision={init,get:el=>instances.get(el)};init();
})();
