"""Build the public core data from the same sources used by standalone artifacts."""
import json
import re
import shutil
from pathlib import Path
from themes import DATA, tokens, original

ROOT = Path(__file__).resolve().parents[1]

def build():
    registry = json.loads((ROOT / 'packages/core/registry/registry.json').read_text())['componentes']
    aliases = json.loads((ROOT / 'packages/core/registry/component-aliases.json').read_text())
    css = (ROOT / 'packages/core/styles/artifact.css').read_text()
    themes = []
    for family in DATA['familias']:
        modes = {}
        for mode in ('light', 'dark'):
            seed = family[mode]
            modes[mode] = original(css, seed) if isinstance(seed, str) else tokens(seed, mode)
        themes.append({'id': family['id'], 'name': family['nombre'], 'modes': modes})
    recipes = [{'id': aliases[r['id']], 'legacyId': r['id'], 'name': r['nombre'], 'category': r['capitulo'],
                'html': r['html'], 'guidance': r['criterio_y_limites'], 'dependencies': r['dependencias']}
               for r in registry]
    data = {'recipes': recipes, 'themes': themes, 'styles': (ROOT / 'packages/core/styles/fonts.css').read_text() + css,
            'modules': {str(p.relative_to(ROOT)): p.read_text() for p in (ROOT / 'packages/core/components').glob('*.js')}}
    target = ROOT / 'packages/core/src/generated-assets.json'
    for name, value in [('assets', {'styles': data['styles'], 'modules': data['modules']}), ('recipes', recipes), ('themes', themes)]:
        encoded = json.dumps(value, ensure_ascii=False, separators=(',', ':'))
        if name == 'assets':
            (target.parent / 'generated-assets.ts').write_text('const data: { styles: string; modules: Record<string, string> } = ' + encoded + ';\nexport default data;\n')
        else:
            (target.parent / ('generated-' + name + '.json')).write_text(encoded + '\n')
    (target.parent / 'generated-ids.ts').write_text('// Generated by scripts/build_core.py.\nexport type RecipeId = ' +
        ' | '.join(json.dumps(r['id']) for r in recipes) + ';\nexport type ThemeFamily = ' +
        ' | '.join(json.dumps(f['id']) for f in themes) + ';\n')
    for package in ('core', 'react'):
        shutil.copytree(ROOT / 'licenses', ROOT / 'packages' / package / 'licenses', dirs_exist_ok=True)
        for name in ('LICENSE', 'NOTICE'):
            (ROOT / 'packages' / package / name).write_bytes((ROOT / name).read_bytes())
    print(f'Built core data: {len(recipes)} recipes, {len(themes)} theme families.')

if __name__ == '__main__':
    build()
