"""Cámara del globo: controles, teclado nativo y gestos mediante PointerEvents controlados."""
import re,json,base64
from comprobar_navegador import call,evaluate,save,ROOT
call('goto','--url','http://127.0.0.1:8768/liftit.html');call('exec','--command','set viewport 1440 960');call('screenshot')
evaluate('window.f=NotaFlota.get(document.querySelector("[data-flota]"));f.stage.scrollIntoView({block:"center",behavior:"instant"});true');call('screenshot')
snap=call('snapshot')['snapshot'];ref=re.search(r'region "Globo operativo de Colombia, desplazable horizontalmente"[^\n]*ref=(e\d+)',snap).group(1);call('focus','--element','@'+ref);call('keypress','--key','ArrowRight');native=evaluate('f.orbitX!==0');controlled=evaluate('f.stage.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true,cancelable:true}));f.orbitX!==0');assert controlled
evaluate('f.stage.dispatchEvent(new KeyboardEvent("keydown",{key:"Home",bubbles:true,cancelable:true}));true');assert evaluate('f.orbitX===0&&f.zoom===1')
checks=evaluate('''(()=>{const out={};f.changeZoom(100);out.max=f.zoom===6;f.changeZoom(.0001);out.min=f.zoom===.5;f.resetView();const before=f.frames;f.stage.blur();document.querySelector('[data-flota-vista=in]').focus();const unfocused=new WheelEvent('wheel',{deltaY:-100,bubbles:true,cancelable:true});f.canvas.dispatchEvent(unfocused);out.wheelOutside=f.zoom===1&&!unfocused.defaultPrevented;f.stage.focus();const focused=new WheelEvent('wheel',{deltaY:-100,bubbles:true,cancelable:true});f.canvas.dispatchEvent(focused);out.wheelInside=f.zoom>1&&focused.defaultPrevented&&!f.frame;f.resetView();const saved=f.canvas.setPointerCapture,captures=[];f.canvas.setPointerCapture=id=>captures.push(id);const event=(type,id,x,y,shift=false)=>f.canvas.dispatchEvent(new PointerEvent(type,{pointerId:id,clientX:x,clientY:y,button:0,buttons:1,pointerType:'touch',shiftKey:shift,bubbles:true}));try{event('pointerdown',81,100,100);event('pointermove',81,180,130);out.rotate=f.orbitX!==0&&f.orbitY!==0;event('pointercancel',81,180,130);out.cancel=f.pointers.size===0&&!f.canvas.classList.contains('arrastrando');f.resetView();event('pointerdown',82,100,100);event('pointermove',82,140,120,true);out.pan=f.panX!==0&&f.panY!==0&&f.orbitX===0;event('pointerup',82,140,120);f.resetView();event('pointerdown',83,100,100);event('pointerdown',84,200,100);event('pointermove',84,240,100);out.pinch=f.zoom>1;event('pointercancel',83,100,100);event('pointercancel',84,240,100);out.capture=captures.length===4;}finally{f.canvas.setPointerCapture=saved;}f.buttons.world.click();f.orbitX=180;f.fit();out.back=f.pins.every(p=>!p.visible)&&f.cityLabels.every(x=>x.el.hidden)&&f.trucks.every(b=>b.hidden)&&f.country.hidden;f.resetView();out.reset=f.orbitX===0&&f.orbitY===0&&f.panX===0&&f.panY===0&&f.zoom===1;out.noRAF=!f.frame;Object.defineProperty(f.motion,'matches',{value:true,configurable:true});f.motion.dispatchEvent(new Event('change'));f.changeZoom(1.25);out.reduced=!f.frame&&f.zoom===1.25&&!f.playing;delete f.motion.matches;f.motion.dispatchEvent(new Event('change'));f.select('LFT-034');out.select=f.focusRoute&&f.zoom===1&&f.orbitX===0&&f.panX===0;return out})()''');assert all(checks.values()),checks
rows=[]
for w,h in [(320,740),(390,844),(1440,960)]:
 call('exec','--command',f'set viewport {w} {h}');call('screenshot')
 row=evaluate('''(()=>{const out=[];for(const theme of ['light','dark','sea','oliva','arcilla','ciruela','liftit','blueprint','hacker']){document.documentElement.dataset.theme=theme;for(const view of ['region','world','route']){f.buttons[view].click();const b=f.surface.getBoundingClientRect(),ends=f.routes.filter(r=>r.mesh.visible).flatMap(r=>[r.curve.getPoint(0),r.curve.getPoint(1)]).map(v=>f.point(v));out.push({theme,view,inside:ends.every(p=>p.x>=0&&p.x<=b.width&&p.y>=0&&p.y<=b.height),documentWidth:document.documentElement.scrollWidth});}}return out})()''')
 assert all(x['inside'] and x['documentWidth']==w for x in row),row;rows.append({'width':w,'views':row})
 evaluate('document.documentElement.dataset.theme="sea";f.buttons.world.click();f.changeZoom(1.25);f.move(25,10);f.stage.scrollIntoView({block:"center",behavior:"instant"});true');call('screenshot');(ROOT/'auditoria/capturas'/f'orbita-flota-{w}.png').write_bytes(base64.b64decode(call('screenshot')['data']))
 print(w,'px: tres encuadres y nueve paletas correctos',flush=True)
cleanup=evaluate('''(()=>{const owner=f.element,table=owner.querySelector('table').outerHTML;f.destroy();const ok=!f.frame&&f.pointers.size===0&&!owner.querySelector('canvas')&&owner.querySelector('table').outerHTML===table;window.f=NotaFlota.init(owner)[0];return ok})()''');assert cleanup
save('orbita-flota.json',{'nativeKeyboardDelivered':native,'controlledKeyboard':controlled,'gestures':checks,'presets':rows,'destroy':cleanup,'limits':['Orca focus/keypress intentado; consultar nativeKeyboardDelivered: si es false, no entregó keydown al DOM. Teclado comprobado además con KeyboardEvent explícito. PointerEvents, rueda y pinch sintéticos; setPointerCapture interceptado para eventos sin dispositivo real.','No prueba física de trackpad ni multitáctil del MacBook. Cámara inmediata, sin RAF ni inercia.']})
print('Cámara, teclado y gestos controlados y limpieza correctos.',flush=True)
