"""Guía viva del catálogo de familias y modos."""
from html import escape
from contract_artifact import ROOT,build,recipe
from themes import DATA

def generate():
 rows=''.join('<tr><th scope="row">'+escape(f['nombre'])+'</th><td>'+escape(f['descripcion'])+'</td><td>Claro / Oscuro / Sistema</td></tr>' for f in DATA['familias'])
 body='''<section id="elegir"><p class="ceja">Apariencia / 15 familias · 30 versiones</p><h2>Un tema, dos formas de verlo.</h2><p>Abre el sol o la luna de la cabecera. Elige una familia y después <strong>Claro, Oscuro o Sistema</strong>. Puedes cambiar de tema sin perder tu modo de lectura.</p><p>Sistema sigue la apariencia de tu dispositivo. Las muestras se actualizan para anticipar el resultado; busca por nombre o filtra la categoría Editores para encontrar Modern, GitHub, Catppuccin y Solarized.</p></section>
<section id="comparar"><h2>El color también organiza.</h2><p>Compara títulos, datos, código, anotaciones y comentarios con el mismo tema. Letras y sonido tienen su propia pestaña: puedes usar cualquier combinación tipográfica sin cambiar la paleta.</p></section>'''
 body+=recipe('barras')+recipe('codigo-lineas')+recipe('terminal')+recipe('apuntes')
 body+='<section id="catalogo"><h2>Una familia por intención.</h2><p>Las referencias de editores son adaptaciones para lectura y datos. Ajustamos ciertos tonos para mantener el contraste en superficies, tablas y código; no son extensiones oficiales.</p></section><figure class="ancho"><div class="tabla-caja" tabindex="0" role="region" aria-label="Catálogo de temas, desplazable"><table><caption>Familias disponibles</caption><thead><tr><th scope="col">Familia</th><th scope="col">Carácter</th><th scope="col">Modo</th></tr></thead><tbody>'+rows+'</tbody></table></div><figcaption>La familia define los colores. El modo decide si el papel es claro u oscuro.</figcaption></figure>'
 body+='''<section id="generar"><h2>También para tu agente.</h2><p>En Claude, Codex o Hermes, pide por ejemplo: “Usa Catppuccin, sigue el sistema y conserva la tipografía Editorial”. La misma elección se puede fijar al generar el archivo:</p></section><figure class="ancho"><div class="codigo"><div class="cab"><span>Crear un documento</span><button type="button" data-copiar="comando-temas" aria-label="Copiar comando">Copiar</button></div><pre tabindex="0" aria-label="Comando para elegir familia y modo"><code id="comando-temas" class="language-bash">python3 scripts/create_artifact.py --contenido contenido.html --titulo 'Mi documento' --tema catppuccin --modo system --salida documento.html</code></pre></div></figure>'''
 (ROOT/'examples/generated/themes.html').write_text(build('Margen · Familias y modos',[{'id':'apariencia','titulo':'Familias y modos','html':body}],'Un catálogo para leer, comparar y elegir.',theme='catppuccin',mode='system',document_id='nota-guia-temas'))
