(async()=>{const results=[],assert=(v,m)=>{if(!v)throw Error(m)},wait=n=>new Promise(r=>setTimeout(r,n)),test=async(name,fn)=>{try{await fn();results.push({name,ok:true})}catch(e){results.push({name,ok:false,error:e.message})}},link=key=>document.querySelector('.catalogo-indice a[href="#receta-'+key+'"]').click();
 await test('65 recetas; mapa y márgenes incorporados al catálogo',()=>{assert(document.querySelectorAll('.receta-copia code').length===65,'registro');assert(document.querySelectorAll('[data-mano]').length===3&&document.querySelectorAll('[data-subrayar]').length===2,'gestos');assert(document.querySelectorAll('.cards-trazadas > a').length===6,'cards');assert(NotaAtencion.get(document.querySelector('[data-atencion]')),'attention map');});
 await test('La nota empieza a trazarse al entrar, después se puede repetir',async()=>{const e=document.getElementById('nota-decision'),s=NotaMano.get(e);assert(!s.played&&!s.animations.length,'se inició oculta');link('manuscrita');await wait(150);assert(s.visible&&s.played&&s.animations.length===s.paths.length,'entrada');const remaining=()=>s.paths.reduce((sum,p)=>sum+parseFloat(getComputedStyle(p).strokeDashoffset),0),before=remaining();await wait(120);assert(remaining()<before,'avance');s.finish();s.play();assert(s.animations.length>0,'repetir');assert(e.querySelector('.sr-only').textContent===s.text,'alternativa textual');});
 await test('Repetir enlace al mismo destino no devuelve a cabecera',async()=>{link('manuscrita');await wait(500);const before=scrollY;link('manuscrita');await wait(500);assert(Math.abs(scrollY-before)<2,'scroll suave pendiente');assert(document.getElementById('receta-manuscrita').getBoundingClientRect().top<160,'destino');});
 await test('Salir cancela animaciones y volver no las reinicia',async()=>{const s=NotaMano.get(document.getElementById('nota-decision'));s.play();document.querySelector('[data-ir=portada]').click();await wait(200);assert(!s.animations.length,'no cancela');link('manuscrita');await wait(120);assert(!s.animations.length,'se repite automáticamente');});
 await test('Subrayados y apuntes son paths; destroy restaura los nodos',async()=>{link('apuntes');await wait(150);for(const e of document.querySelectorAll('[data-subrayar]'))assert(NotaMano.get(e).paths.length===1,'subrayado');const e=document.getElementById('apunte-izquierdo'),s=NotaMano.get(e),text=s.text;s.destroy();assert(e.textContent===text&&!e.querySelector('svg')&&!NotaMano.get(e),'destroy');NotaMano.init(e);assert(NotaMano.get(e),'init');});
 await test('Texto fuera del alfabeto y palabras largas no se comprimen',()=>{for(const text of ['Texto con MAYÚSCULAS','mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm']){const e=document.createElement('p');e.className='manuscrita';e.dataset.mano='';e.textContent=text;document.body.append(e);assert(NotaMano.init(e)[0]===null&&e.textContent===text&&!e.querySelector('svg'),'fallback');e.remove();}});
 await test('Áreas exactas, suma total y particiones sin superposición',()=>{const s=NotaAtencion.get(document.querySelector('[data-atencion]'));assert(s.total===212,'total');let sum=0;for(const a of s.tiles){sum+=a.w*a.h;assert(Math.abs(a.w*a.h/(1000*380)-a.value/212)<1e-10,'proporción');for(const b of s.tiles){if(a===b)continue;assert(Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)<1e-7||Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)<1e-7,'solapamiento');}}assert(Math.abs(sum-380000)<1e-6,'cobertura');s.select(7);assert(s.status.textContent.includes('Otros')&&s.status.textContent.includes('3 horas'),'selección');});
 await test('Mapa conserva tabla al destruir y rechaza negativos',()=>{const e=document.querySelector('[data-atencion]'),s=NotaAtencion.get(e),text=e.querySelector('table').textContent;s.destroy();assert(e.querySelector('table').textContent===text&&!NotaAtencion.get(e),'tabla');NotaAtencion.init(e);const copy=document.createElement('figure');copy.dataset.atencion='';copy.append(e.querySelector('.tabla-caja').cloneNode(true));copy.querySelector('td').dataset.valor='-1';document.body.append(copy);assert(NotaAtencion.init(copy)[0]===null&&copy.querySelector('table'),'negativo');copy.remove();});
 await test('Audio comienza apagado y no admite activación ni hover sintéticos',()=>{assert(!NotaAudio.enabled&&NotaAudio.plays===0,'apagado');document.querySelector('[data-audio-global]').click();document.querySelector('[data-audio-hover]').dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerType:'mouse',clientX:10,clientY:20}));assert(!NotaAudio.enabled&&NotaAudio.plays===0,'eventos sintéticos');});
 return {results,failed:results.filter(r=>!r.ok).length};})()
