(async()=>{
 const results=[],assert=(x,m)=>{if(!x)throw Error(m)},test=async(name,fn)=>{try{await fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.message});}},wait=()=>new Promise(r=>setTimeout(r,100)),go=id=>{document.querySelector('[data-ir='+id+']').click();scrollTo({top:0,behavior:'instant'});};
 await test('Pin flotante y burbuja sin desplazar documento',()=>{go('portada');getSelection().removeAllRanges();const target=document.querySelector('.pagina.viva .bajada'),before=target.getBoundingClientRect().toJSON(),height=document.documentElement.scrollHeight;document.querySelector('.revision-barra [data-revision-modo]').click();target.dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:before.left+before.width*.6,clientY:before.top+before.height*.5}));const editor=document.querySelector('[data-revision-editor]');assert(editor.open&&!editor.matches(':modal'),'editor no modal');assert(editor.getBoundingClientRect().width<=304,'burbuja ancha');document.querySelector('[data-revision-texto]').value='Mejorar este espacio sin mover el contenido.';document.querySelector('[data-revision-guardar]').click();const after=target.getBoundingClientRect();assert(Math.abs(after.top-before.top)<.1&&Math.abs(after.height-before.height)<.1&&document.documentElement.scrollHeight===height,'layout alterado');const pin=document.querySelector('.revision-marca');assert(pin.parentElement.classList.contains('revision-capa'),'pin dentro del flujo');const note=NotaRevision.get(document.querySelector('[data-revision]')).comments[0];assert(Math.abs(note.x-.6)<.01&&Math.abs(note.y-.5)<.01,'coordenadas');assert(document.querySelector('[data-revision-prompt]').textContent.includes('60% horizontal'),'contexto del prompt');});
 await test('Pines se ocultan entre capítulos y regresan con su contenido',()=>{go('tablas');assert(document.querySelector('.revision-marca').hidden,'pin de otro capítulo visible');go('portada');assert(!document.querySelector('.revision-marca').hidden,'pin no regresa');document.querySelector('.revision-marca').click();assert(document.querySelector('[data-revision-texto]').value.includes('Mejorar'),'abrir comentario');document.querySelector('[data-revision-cancelar]').click();});
 await test('Tabla: menú de orden explícito, filtro, grupo y columnas',async()=>{go('tablas');const el=document.querySelector('[data-explorador]'),form=el.querySelector('form');el.querySelector('[data-orden-col="3"][data-direccion="-1"]').click();assert(el.querySelector('tbody tr').textContent.includes('140.000'),'descendente');form.elements.estado.value='Confirmado';form.elements.grupo.value='1';form.dispatchEvent(new Event('change'));assert(el.querySelectorAll('tbody').length===3&&el.querySelector('[data-explorador-estado]').textContent.includes('280.000'),'filtrar agrupar');const col=form.querySelector('[data-columna="1"]');col.checked=false;col.dispatchEvent(new Event('change',{bubbles:true}));assert(el.querySelector('thead th:nth-child(2)').hidden,'columna');form.reset();await wait();assert(!el.querySelector('thead th:nth-child(2)').hidden,'reset columnas');});
 await test('Visor: proporción y orientación reales, ajuste visual',()=>{go('prototipos');const el=document.querySelector('[data-visor]'),v=NotaVisores.get(el);v.setWidth('390');v.setAspect('9/16');assert(parseFloat(v.host.style.width)===390&&Math.abs(parseFloat(v.host.style.height)-693.333)<.1,'9:16');el.querySelector('[data-girar-visor]').click();assert(Math.abs(parseFloat(v.host.style.width)-693.333)<.1&&parseFloat(v.host.style.height)===390,'rotar');el.querySelector('[data-ajustar-visor]').click();assert(v.host.getBoundingClientRect().width<=el.querySelector('.visor-caja').clientWidth+.1,'ajustar');v.setAspect('auto');v.setWidth('390');v.fit=false;v.layout();});
 await test('Importar y recuperar HTML conserva el visor',()=>{const el=document.querySelector('[data-visor]'),v=NotaVisores.get(el);v.loadHTML('<p>Una vista propia</p>');assert(v.shadow.textContent.includes('Una vista propia'),'importar');let denied=false;try{v.loadHTML('<script>alert(1)</script>');}catch{denied=true;}assert(denied,'script permitido');el.querySelector('[data-reiniciar-visor]').click();assert(v.shadow.textContent.includes('Tu primer registro'),'reiniciar');});
 await test('Sonido central apagado; clic sintético no activa audio',()=>{const button=document.querySelector('[data-audio-global]');assert(!NotaAudio.enabled,'inicial');button.click();assert(!NotaAudio.enabled,'sintético');assert(document.querySelectorAll('[data-ver-escritura]').length>0,'acceso escritura');});
 await test('Textura coincide entre cuerpo y barra de capítulos',()=>{document.documentElement.setAttribute('data-trama','');assert(getComputedStyle(document.body).backgroundImage===getComputedStyle(document.querySelector('.barra.capitulos')).backgroundImage,'textura diferente');assert(getComputedStyle(document.body).backgroundImage.includes('data:image'),'falta grano');});
 await test('Nueve lenguajes coloreados y terminal con tokens',()=>{assert(document.querySelectorAll('#codigo-poliglota code[data-lenguaje]').length===9,'lenguajes');for(const code of document.querySelectorAll('#codigo-poliglota code'))assert(code.querySelector('span'),'sin tokens '+code.dataset.lenguaje);assert(document.querySelector('.terminal .codigo-numero'),'terminal');});
 return {results,failed:results.filter(r=>!r.ok).length};
})()
