(async()=>{
 const results=[],assert=(ok,msg)=>{if(!ok)throw Error(msg)},wait=ms=>new Promise(r=>setTimeout(r,ms)),test=async(name,fn)=>{try{await fn();results.push({name,ok:true})}catch(e){results.push({name,ok:false,error:e.message})}};
 document.querySelector('[data-ir=piezas]').click();await wait(350);
 await test('código numerado conserva fuente, saltos y selección',()=>{const code=document.querySelector('#codigo-lineas-fuente');assert(code.querySelectorAll('.codigo-linea').length===6,'líneas');assert([...code.querySelectorAll('.destacada')].map(e=>e.dataset.numero).join(',')==='3,6','destacadas');assert(code.textContent.split('\n').length===6&&code.textContent.startsWith('def resumir('),'copia');assert(code.querySelectorAll('.kw,.str').length>6,'sintaxis');const rects=[...code.querySelectorAll('.codigo-linea')].map(e=>e.getBoundingClientRect());assert(Math.abs(rects[1].top-rects[0].bottom)<1,'doble interlineado');});
 await test('actividad alcanza su escala y explica valor, total y porcentaje',()=>{const el=document.querySelector('[data-actividad]'),cells=el.querySelectorAll('.actividad-celda');assert(cells.length===8,'períodos');cells[7].click();assert(el.querySelector('[data-actividad-estado]').textContent.includes('8 acciones. 26.7 % de las 30'),'contexto');assert(el.querySelector('[data-actividad-escala]').textContent.endsWith('7–8'),'máximo');});
 await test('actividad cero y dato inválido preservan la tabla',()=>{const el=document.querySelector('[data-actividad]'),cells=[...el.querySelectorAll('td[data-valor]')],original=cells.map(e=>e.dataset.valor);NotaPiezasEditoriales.get(el).destroy();cells.forEach(e=>e.dataset.valor='0');NotaPiezasEditoriales.init(el);assert(el.querySelector('[data-actividad-escala]').textContent==='0','escala inalcanzable');assert(el.querySelector('table'),'alternativa');NotaPiezasEditoriales.get(el).destroy();cells[0].dataset.valor='-1';NotaPiezasEditoriales.init(el);assert(el.querySelectorAll('.actividad-celda').length===0&&el.querySelector('[data-actividad-estado]').textContent.includes('No se puede'),'dato inválido');NotaPiezasEditoriales.get(el).destroy();cells.forEach((e,i)=>e.dataset.valor=original[i]);NotaPiezasEditoriales.init(el);NotaPiezasEditoriales.init(el);assert(el.querySelectorAll('.actividad-celda').length===8,'init idempotente');});
 await test('marcos no pisan decoración ni alteran contenido',()=>{const wide=[...document.querySelectorAll('.nota-estandar :is(.ancho,.amplio)')];assert(wide.every(el=>el.querySelector(':scope > .marco-lineas')),'marco ausente');for(const el of wide){const line=el.querySelector('.marco-lineas');assert(getComputedStyle(line,'::before').borderTopStyle==='dotted','tipo');assert(getComputedStyle(line,'::before').maskImage.includes('gradient'),'difusión');assert(getComputedStyle(el).maskImage==='none','contenido enmascarado');const a=el.getBoundingClientRect(),b=line.getBoundingClientRect();if(a.height)assert(Math.abs(a.top-b.top)<=1&&Math.abs(a.left-b.left)<=1,'margen heredado en el marco');}NotaPiezasEditoriales.init();assert(document.querySelectorAll('.marco-lineas').length===wide.length,'duplicado');});
 return {results,failed:results.filter(r=>!r.ok).length};
})()
