(async()=>{
 const results=[],assert=(v,m)=>{if(!v)throw Error(m)},wait=()=>new Promise(r=>setTimeout(r,100)),test=async(name,fn)=>{try{await fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.message});}};
 const go=page=>{document.querySelector('[data-ir='+page+']').click();scrollTo({top:0,behavior:'instant'});};
 await test('44 recetas y HTML coloreado sin cambiar fuente',()=>{assert(document.querySelectorAll('.receta-copia code').length===44,'cantidad');const code=document.querySelector('#biblioteca-codigo-archivo');assert(code.querySelectorAll('.kw,.str,.codigo-atributo').length>20,'tokens');assert(code.textContent.startsWith('<section class="pieza ancho"'),'texto alterado');});
 await test('Tabla filtra, agrupa y ordena las filas visibles',async()=>{go('tablas');const el=document.querySelector('[data-explorador]'),form=el.querySelector('form');form.elements.estado.value='Confirmado';form.elements.grupo.value='1';form.dispatchEvent(new Event('change'));assert(el.querySelectorAll('tbody').length===3,'grupos');assert(el.querySelector('[data-explorador-estado]').textContent.includes('280.000'),'suma filtrada');form.elements.buscar.value='revision';form.dispatchEvent(new Event('input'));assert(el.querySelectorAll('tbody tr').length===2,'búsqueda acentuada con grupo');form.reset();await wait();el.querySelector('[data-orden-col="3"][data-direccion="-1"]').click();assert(el.querySelector('tbody tr').textContent.includes('140.000'),'orden descendente');NotaExplorador.get(el).destroy();assert(el.querySelectorAll('tbody tr').length===6,'destroy');NotaExplorador.init();});
 await test('Cards conservan tres tipos y enlaces reales',()=>{assert(document.querySelectorAll('.card-editorial').length===3,'cards');assert(document.querySelector('.card-dato meter').value===12,'dato');});
 await test('Visor carga HTML local, cambia ancho y reinicia',()=>{go('prototipos');const el=document.querySelector('[data-visor]'),v=NotaVisores.get(el);v.loadHTML('<style>p{font-size:20px}</style><p>Mi prototipo propio</p>');assert(v.shadow.textContent.includes('Mi prototipo propio'),'importación');v.setWidth('1024');assert(v.host.getBoundingClientRect().width===1024,'escritorio');v.setWidth('390');assert(v.host.getBoundingClientRect().width===390,'móvil');let rejected=false;try{v.loadHTML('<iframe src="https://example.com"></iframe>');}catch{rejected=true;}assert(rejected&&v.shadow.textContent.includes('Mi prototipo propio'),'rechazo conserva anterior');el.querySelector('[data-reiniciar-visor]').click();assert(v.shadow.textContent.includes('Tu primer registro'),'reset original');});
 await test('Comentario por teclado: guardar marca y prompt',()=>{go('portada');const button=document.querySelector('.revision-barra [data-revision-modo]');getSelection().removeAllRanges();button.click();const target=document.querySelector('.pagina.viva .bajada');assert(target.tabIndex===0,'fragmento accesible');target.focus();target.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));const dialog=document.querySelector('[data-revision-editor]');assert(dialog.open&&document.activeElement.matches('[data-revision-texto]'),'editor con foco');document.querySelector('[data-revision-texto]').value='Aumentar el espacio antes de este párrafo.';document.querySelector('[data-revision-guardar]').click();assert(document.querySelectorAll('.revision-marca').length===1,'marca');assert(document.querySelector('[data-revision-prompt]').textContent.includes('Aumentar el espacio'),'prompt');assert(!target.hasAttribute('tabindex'),'restaurar foco temporal');});
 await test('Comentario: editar, navegar desde lista y borrar',()=>{document.querySelector('.revision-marca').click();document.querySelector('[data-revision-texto]').value='Dar más aire a la introducción.';document.querySelector('[data-revision-guardar]').click();document.querySelector('.revision-barra [data-revision-lista]').click();const panel=document.querySelector('[data-revision-panel]');assert(panel.open,'panel');assert(panel.textContent.includes('Dar más aire'),'editado');panel.querySelector('li a').click();assert(!panel.open,'volver al fragmento');document.querySelector('.revision-barra [data-revision-lista]').click();[...panel.querySelectorAll('li button')].find(b=>b.textContent==='Borrar').click();assert(!document.querySelector('.revision-marca'),'eliminado');panel.querySelector('[data-revision-cerrar]').click();});
 await test('Revision destroy/init limpia barra y listeners',()=>{const el=document.querySelector('[data-revision]');NotaRevision.get(el).destroy();assert(!document.querySelector('.revision-barra'),'destroy');NotaRevision.init();assert(document.querySelectorAll('.revision-barra').length===1,'init');});
 await test('Sonido de escritura apagado sin gesto explícito',()=>{const el=document.querySelector('[data-escritura]'),audio=NotaSonido.get(el);assert(!audio.enabled&&audio.audio===null,'audio automático');});
 return {results,failed:results.filter(r=>!r.ok).length};
})()
