(async()=>{
 const results=[],assert=(v,m)=>{if(!v)throw Error(m)},near=(a,b)=>Math.abs(a-b)<1e-5,test=async(name,fn)=>{try{await fn();results.push({name,ok:true})}catch(e){results.push({name,ok:false,error:e.message})}},get=type=>NotaAnalitica.get(document.querySelector('[data-analitica='+type+']'));
 await test('Siete SVG y tres nuevas escenas, sin errores de inicialización',()=>{assert(document.querySelectorAll('.nota-analitica').length===7,'SVG');assert(!document.querySelector('[data-error-analitica],[data-error-escena]'),'error');for(const type of ['columnas','arcos','almacen'])assert(NotaEscena.get(document.querySelector('[data-escena='+type+']'))?.renderer,'WebGL '+type);});
 await test('Calendario distingue cero, ausencia y máximo observado',()=>{const c=get('calendario');assert(c.max===24,'máximo');assert(c.chart.querySelectorAll('[data-valor="ausente"]').length===3,'ausencias');assert(c.chart.querySelector('[data-valor="0"]').getAttribute('fill')==='var(--calor-0)','cero');assert(c.chart.querySelector('[data-valor="24"]').getAttribute('fill')==='var(--calor-4)','máximo');});
 await test('Torta cambia forma sin alterar total ni valores',()=>{const c=get('torta'),source=c.element.querySelector('table').textContent;assert(c.total===100&&c.chart.querySelectorAll('[data-registro]').length===4,'total/sectores');c.toggle.click();assert(!c.donut&&c.total===100,'toggle');assert(c.element.querySelector('table').textContent===source,'fuente');c.toggle.click();});
 await test('Áreas alcanzan el total de 80 con fechas a distancia real',()=>{const c=get('areas'),points=c.chart.querySelectorAll('circle');assert(c.domain[1]===80,'dominio');assert(near(+points[4].getAttribute('cy'),60),'último total');const xs=[...points].map(p=>+p.getAttribute('cx'));assert(near((xs[1]-xs[0])/(xs[2]-xs[1]),30/31),'distancia mensual');});
 await test('Caja alcanza mínimo 15 y máximo 110; mediana dentro del cuartil',()=>{const c=get('caja');assert(c.domain[0]===15&&c.domain[1]===110,'dominio');for(const r of c.model.rows)assert(r.values[1]<=r.values[2]&&r.values[2]<=r.values[3],'cuartiles');assert(near(+c.chart.querySelectorAll('[data-registro]')[2].querySelector('line').getAttribute('x2'),640),'máximo real');});
 await test('OHLC usa extremos globales y cuerpo apertura/cierre',()=>{const c=get('velas');assert(c.domain[0]===96&&c.domain[1]===119,'extremos');const g=c.chart.querySelector('[data-registro="0"]');assert(near(+g.querySelector('rect').getAttribute('height'),8/23*250),'cuerpo');assert(g.querySelector('rect').getAttribute('fill')==='var(--grafica-papel)','sube hueca');});
 await test('Mapas: área de burbujas y grosor de rutas proporcionales',()=>{const c=get('burbujas'),nodes=c.chart.querySelectorAll('[data-registro]');assert(near((+nodes[0].getAttribute('r'))**2/(+nodes[3].getAttribute('r'))**2,4),'área/radio');const paths=get('rutas').chart.querySelectorAll('[data-registro]');assert(near(+paths[0].getAttribute('stroke-width')/+paths[2].getAttribute('stroke-width'),80/30),'grosor');assert(document.querySelectorAll('script[src*="three"]').length===1,'Three repetido');});
 await test('Selección por control y por marca conserva el dato exacto',()=>{const c=get('burbujas');c.select.value='2';c.select.dispatchEvent(new Event('change'));assert(c.status.textContent.includes('Cali')&&c.status.textContent.includes('120'),'selector');c.chart.querySelector('[data-registro="0"]').dispatchEvent(new MouseEvent('click',{bubbles:true}));assert(c.selected===0&&c.status.textContent.includes('240'),'marca');c.choose(null);});
 await test('Tres escenas conservan magnitudes, no sólo formas',()=>{const col=NotaEscena.get(document.querySelector('[data-escena=columnas]')),arc=NotaEscena.get(document.querySelector('[data-escena=arcos]')),store=NotaEscena.get(document.querySelector('[data-escena=almacen]'));assert(near(col.items[0].geometry.parameters.height/col.items[3].geometry.parameters.height,4),'columnas');assert(near(arc.items[0].geometry.parameters.radius**2/arc.items[2].geometry.parameters.radius**2,80/30),'sección de tubos');assert(near(store.items[0].geometry.parameters.height,8/12*1.8),'ocupación');assert(near((store.items[1].position.x-store.items[0].position.x)/(store.items[2].position.z-store.items[0].position.z),4/6),'X/Z en la misma escala de metros');for(const s of [col,arc,store])for(const mesh of s.items)assert([...mesh.geometry.attributes.position.array].every(Number.isFinite),'geometría finita');});
 function clone(type,change){const original=document.querySelector('[data-analitica='+type+']'),copy=original.cloneNode(true);copy.querySelectorAll('.grafica-titulo,.analitica-controles,.analitica-caja,.analitica-leyenda,.analitica-estado').forEach(n=>n.remove());copy.removeAttribute('id');change(copy);document.body.append(copy);return copy;}
 await test('Entradas inválidas conservan tabla y muestran error',()=>{for(const [type,change] of [['torta',c=>c.querySelector('td').dataset.valor='-1'],['velas',c=>c.querySelector('td').dataset.valor='999'],['caja',c=>c.querySelector('td').dataset.valor='999'],['calendario',c=>c.querySelector('tbody th').textContent='2026-02-30'],['burbujas',c=>c.querySelector('td').dataset.valor='90']]){const c=clone(type,change);assert(NotaAnalitica.init(c)[0]===null&&c.querySelector('table')&&c.querySelector('[data-error-analitica]'),type);c.remove();}});
 await test('Cero, categoría única, fechas repetidas y reinicialización',()=>{const one=clone('torta',c=>{[...c.querySelectorAll('tbody tr')].slice(1).forEach(r=>r.remove());});const instance=NotaAnalitica.init(one)[0];assert(instance.chart.querySelector('circle'),'100 % de un sector');const source=one.querySelector('table').outerHTML;instance.destroy();assert(!NotaAnalitica.get(one)&&one.querySelector('table').outerHTML===source,'destroy');const again=NotaAnalitica.init(one)[0];assert(again&&NotaAnalitica.init(one)[0]===again,'idempotencia');again.destroy();one.remove();const dates=clone('areas',c=>c.querySelectorAll('tbody th')[1].textContent=c.querySelector('tbody th').textContent);assert(NotaAnalitica.init(dates)[0]===null,'fechas repetidas');dates.remove();const zero=clone('torta',c=>c.querySelectorAll('td').forEach(d=>d.dataset.valor='0'));assert(NotaAnalitica.init(zero)[0]===null,'total cero');zero.remove();});
 await test('Magnitudes pequeñas/grandes legibles sin convertir valores en cero',()=>{for(const value of [1e-5,1e12]){const c=clone('areas',e=>e.querySelectorAll('td').forEach(d=>d.dataset.valor=String(value)));const chart=NotaAnalitica.init(c)[0];assert(chart.chart.textContent.includes('E'),'notación legible');assert(chart.domain[1]>0,'dominio positivo');for(const t of chart.chart.querySelectorAll('text')){const b=t.getBBox();assert(b.x>=-1&&b.x+b.width<=721,'rótulo numérico cortado');}chart.destroy();c.remove();}});
 await test('Todas las marcas SVG tienen coordenadas finitas y texto dentro del lienzo',()=>{document.querySelector('[data-ir=graficas]').click();for(const c of document.querySelectorAll('.analitica-caja svg')){assert(!/NaN|Infinity/.test(c.outerHTML),'coordenada inválida');for(const t of c.querySelectorAll('text,path,circle,rect')){const b=t.getBBox(),v=c.viewBox.baseVal;if(b.width)assert(b.x>=-1&&b.x+b.width<=v.width+1&&b.y>=-1&&b.y+b.height<=v.height+1,'etiqueta fuera: '+t.textContent);}}});
 return {results,failed:results.filter(r=>!r.ok).length};
})()
